// WildDex entries, grouped into album "sheets".
//
// Each entry maps to one or more ImageNet class indices (`c`) - the scanner
// sums the model's probability over those classes, so e.g. every dog breed
// counts toward "Dog" and is remembered as a separate form.
//
// Keys: k key, n name, s scientific name, e emoji (silhouette for locked
// stamps), r rarity (1 common .. 4 legendary), c classes, h habitat,
// d diet, z size, t dex entry text, f fun fact.

const range = (a, b) => Array.from({ length: b - a + 1 }, (_, i) => a + i);

export const RARITY = {
  1: { name: 'Common', value: 10 },
  2: { name: 'Uncommon', value: 25 },
  3: { name: 'Rare', value: 50 },
  4: { name: 'Legendary', value: 100 },
};

export const SETS = [
  {
    id: 'home', name: 'Home & Pets', icon: '🏠', color: '#e76f51',
    entries: [
      { k: 'dog', n: 'Dog', s: 'Canis familiaris', e: '🐕', r: 1, c: range(151, 268), h: 'Homes worldwide', d: 'Omnivore', z: '15–90 cm at shoulder',
        t: 'Humanity\'s oldest companion, domesticated from wolves more than 15,000 years ago. Its nose holds up to 300 million scent receptors.',
        f: 'There are hundreds of breeds — every new breed you scan is logged as a new form.' },
      { k: 'cat', n: 'Cat', s: 'Felis catus', e: '🐈', r: 1, c: range(281, 285), h: 'Homes, farms and streets', d: 'Carnivore', z: '23–25 cm at shoulder',
        t: 'A silent stalker that has lived alongside people for about 10,000 years, first earning its keep by hunting grain-stealing rodents.',
        f: 'Cats can swivel each ear independently using 32 muscles.' },
      { k: 'rabbit', n: 'Rabbit', s: 'Family Leporidae', e: '🐇', r: 1, c: [330, 332], h: 'Meadows, burrows and pet hutches', d: 'Herbivore', z: '20–50 cm',
        t: 'A twitchy-nosed grazer whose eyes sit high on the sides of its head, giving it a nearly all-round view to spot predators.',
        f: 'A rabbit\'s teeth never stop growing — chewing hay keeps them worn down.' },
      { k: 'hamster', n: 'Hamster', s: 'Subfamily Cricetinae', e: '🐹', r: 1, c: [333], h: 'Dry steppes; pet homes', d: 'Omnivore', z: '5–34 cm',
        t: 'Stuffs food into stretchy cheek pouches that reach back to its shoulders, then hauls the stash home to its burrow.',
        f: 'Most pet hamsters are nocturnal and can run several kilometres a night on a wheel.' },
      { k: 'guinea-pig', n: 'Guinea Pig', s: 'Cavia porcellus', e: '🐹', r: 1, c: [338], h: 'Andes origin; pet homes', d: 'Herbivore', z: '20–25 cm',
        t: 'A chatty rodent from the Andes that squeaks, purrs and "wheeks" to its herd. Happy ones leap straight up in a hop called "popcorning".',
        f: 'Like humans, guinea pigs can\'t make their own vitamin C and must get it from food.' },
      { k: 'goldfish', n: 'Goldfish', s: 'Carassius auratus', e: '🐠', r: 1, c: [1], h: 'Ponds and aquariums', d: 'Omnivore', z: '10–20 cm',
        t: 'Bred from wild carp in China over 1,000 years ago, it now shimmers in ponds and bowls across the globe.',
        f: 'Goldfish memories last months, not three seconds — they can be trained to respond to sounds and colours.' },
      { k: 'ferret', n: 'Ferret', s: 'Mustela species', e: '🦡', r: 2, c: [358, 359], h: 'Pet homes; prairies (wild kin)', d: 'Carnivore', z: '35–50 cm with tail',
        t: 'A long, bendy hunter built to chase prey down burrows. Its wild cousin, the black-footed ferret, was once thought to be extinct.',
        f: 'Excited ferrets do a bouncing, sideways hop known as the "weasel war dance".' },
      { k: 'african-grey', n: 'African Grey Parrot', s: 'Psittacus erithacus', e: '🦜', r: 2, c: [87], h: 'Central African rainforests', d: 'Herbivore (seeds, fruit)', z: '33 cm',
        t: 'A brilliant mimic that can learn hundreds of words and use some of them with apparent meaning.',
        f: 'Alex, a famous African grey, learned to name colours and shapes and count up to six.' },
      { k: 'cockroach', n: 'Cockroach', s: 'Order Blattodea', e: '🪳', r: 1, c: [314], h: 'Buildings and forests worldwide', d: 'Omnivore (scavenger)', z: '1–8 cm',
        t: 'An ancient survivor whose roach-like ancestors scuttled about over 300 million years ago. It can flatten itself to squeeze through gaps thinner than a coin.',
        f: 'Of about 4,600 cockroach species, only around 30 live alongside people as pests.' },
      { k: 'fly', n: 'Fly', s: 'Order Diptera', e: '🪰', r: 1, c: [308], h: 'Everywhere', d: 'Liquids and decaying matter', z: '0.5–1 cm',
        t: 'A buzzing acrobat that tastes with its feet and sees the world through thousands of lenses in each compound eye.',
        f: 'Flies process images so fast that a swatter seems to move in slow motion to them.' },
    ],
  },
  {
    id: 'farm', name: 'Farm & Country', icon: '🚜', color: '#c9a227',
    entries: [
      { k: 'cow', n: 'Cow', s: 'Bos taurus', e: '🐄', r: 1, c: [345], h: 'Farms and pastures', d: 'Herbivore', z: '1.2–1.5 m at shoulder',
        t: 'A gentle grazer with a four-chambered stomach that re-chews its food as cud to squeeze out every nutrient.',
        f: 'Cows form close friendships and show signs of stress when separated from their favourite herd-mates.' },
      { k: 'horse', n: 'Horse', s: 'Equus caballus', e: '🐎', r: 1, c: [339], h: 'Farms, stables and plains', d: 'Herbivore', z: '1.4–1.8 m at shoulder',
        t: 'A powerful runner that can doze standing up by locking its legs. Its eyes are among the largest of any land mammal.',
        f: 'Horses can\'t breathe through their mouths — only through their noses.' },
      { k: 'pig', n: 'Pig', s: 'Sus domesticus', e: '🐖', r: 1, c: [341], h: 'Farms worldwide', d: 'Omnivore', z: 'Up to 1 m at shoulder',
        t: 'A clever snuffler that roots through soil with its sensitive snout. Pigs wallow in mud to keep cool because they barely sweat.',
        f: 'Pigs have learned to play simple video games using a joystick.' },
      { k: 'sheep', n: 'Sheep', s: 'Ovis aries', e: '🐑', r: 1, c: [348], h: 'Farms and hillsides', d: 'Herbivore', z: '0.7–1 m at shoulder',
        t: 'A flocking grazer whose wool keeps growing all its life. The curling horns of a ram grow bigger every year.',
        f: 'Sheep can recognise at least 50 other sheep faces and remember them for years.' },
      { k: 'chicken', n: 'Chicken', s: 'Gallus gallus domesticus', e: '🐓', r: 1, c: [7, 8], h: 'Farms and backyards', d: 'Omnivore', z: '40–70 cm tall',
        t: 'Descended from the red junglefowl, it is now the most numerous bird on Earth — there are more chickens than people.',
        f: 'Proteins from a T. rex fossil most closely matched those of chickens and ostriches.' },
      { k: 'mallard', n: 'Mallard Duck', s: 'Anas platyrhynchos', e: '🦆', r: 1, c: [97], h: 'Ponds, rivers, parks and farms', d: 'Omnivore', z: '50–65 cm',
        t: 'The dabbling duck behind almost every farm duck breed. Males flash an iridescent green head; females wear camouflaging brown.',
        f: 'Its feathers are waterproofed with oil from a gland near the base of the tail.' },
      { k: 'goose', n: 'Goose', s: 'Tribe Anserini', e: '🪿', r: 1, c: [99], h: 'Lakes, fields and farms', d: 'Herbivore', z: '75–110 cm',
        t: 'A loud, loyal bird that often mates for life and fiercely guards its goslings with hisses and wing-slaps.',
        f: 'Migrating geese fly in a V so each bird rides the updraft from the wingtip ahead.' },
      { k: 'water-buffalo', n: 'Water Buffalo', s: 'Bubalus bubalis', e: '🐃', r: 2, c: [346], h: 'Rice paddies and wetlands of Asia', d: 'Herbivore', z: '1.5–1.9 m at shoulder',
        t: 'A mighty wallower that pulls ploughs through flooded paddies. Its rich milk makes true mozzarella.',
        f: 'There are around 200 million domestic water buffalo in the world.' },
      { k: 'llama', n: 'Llama', s: 'Lama glama', e: '🦙', r: 2, c: [355], h: 'Andes; farms worldwide', d: 'Herbivore', z: '1.7–1.8 m at head',
        t: 'A sure-footed pack animal of the Andes. When annoyed it may spit — mostly at other llamas.',
        f: 'Farmers use llamas to guard sheep because they boldly confront foxes and coyotes.' },
      { k: 'hare', n: 'Hare', s: 'Genus Lepus', e: '🐇', r: 2, c: [331], h: 'Open fields and meadows', d: 'Herbivore', z: '50–70 cm',
        t: 'A long-legged sprinter that relies on speed rather than burrows, bursting away at up to 70 km/h.',
        f: 'Unlike rabbits, baby hares are born furred with eyes open, ready to run.' },
      { k: 'quail', n: 'Quail', s: 'Family Phasianidae', e: '🐦', r: 2, c: [85], h: 'Grasslands and farmland', d: 'Omnivore (seeds, insects)', z: '15–20 cm',
        t: 'A plump little ground bird that prefers to run and hide in the grass, exploding into flight only when startled.',
        f: 'Each female Japanese quail lays eggs with her own consistent speckle pattern.' },
      { k: 'partridge', n: 'Partridge', s: 'Perdix perdix', e: '🐦', r: 2, c: [86], h: 'Farmland and hedgerows', d: 'Omnivore', z: '30 cm',
        t: 'A round, rust-faced game bird that lives in family groups called coveys, huddling together on cold nights.',
        f: 'Grey partridge chicks eat mostly insects during their first weeks of life.' },
    ],
  },
  {
    id: 'backyard', name: 'Backyard & Park', icon: '🌳', color: '#4a9d5b',
    entries: [
      { k: 'squirrel', n: 'Tree Squirrel', s: 'Genus Sciurus & kin', e: '🐿️', r: 1, c: [335], h: 'Parks, gardens and woodland', d: 'Omnivore (nuts, seeds)', z: '45–70 cm with tail',
        t: 'A bushy-tailed acrobat that buries thousands of nuts each autumn and finds many of them again by memory and smell.',
        f: 'Forgotten nuts sprout into trees — squirrels are accidental forest planters.' },
      { k: 'robin', n: 'American Robin', s: 'Turdus migratorius', e: '🐦', r: 1, c: [15], h: 'Lawns and woodland of North America', d: 'Omnivore (worms, berries)', z: '25 cm',
        t: 'A red-breasted thrush that tilts its head on lawns, watching and listening for earthworms before it pounces.',
        f: 'A robin can eat around 4 metres of earthworms in a single day.' },
      { k: 'house-finch', n: 'House Finch', s: 'Haemorhous mexicanus', e: '🐦', r: 1, c: [12], h: 'Towns and deserts of North America', d: 'Herbivore (seeds)', z: '13–14 cm',
        t: 'A cheerful songbird whose males glow red on the head and chest. The redder the male, the more females like him.',
        f: 'The red comes from pigments in its food — a better diet means a brighter bird.' },
      { k: 'goldfinch', n: 'Goldfinch', s: 'Carduelis carduelis', e: '🐦', r: 1, c: [11], h: 'Gardens and meadows of Europe & Asia', d: 'Herbivore (seeds)', z: '12–13 cm',
        t: 'A jewel-bright finch with a red face and golden wing bars that plucks seeds from thistles with its fine beak.',
        f: 'A flock of goldfinches is called a "charm".' },
      { k: 'junco', n: 'Dark-eyed Junco', s: 'Junco hyemalis', e: '🐦', r: 2, c: [13], h: 'Forests and gardens of North America', d: 'Omnivore (seeds, insects)', z: '14–16 cm',
        t: 'A slate-grey sparrow that flashes white outer tail feathers as it hops. Its winter arrival earned it the nickname "snowbird".',
        f: 'Juncos are among the most abundant forest birds in North America.' },
      { k: 'chickadee', n: 'Chickadee', s: 'Genus Poecile', e: '🐦', r: 1, c: [19], h: 'Woodland and backyards', d: 'Omnivore (insects, seeds)', z: '12–15 cm',
        t: 'A tiny, fearless bird that calls its own name: "chick-a-dee-dee-dee". More "dees" means a bigger threat nearby.',
        f: 'Each autumn chickadees grow new brain cells to help remember where they hid their food.' },
      { k: 'jay', n: 'Jay', s: 'Family Corvidae', e: '🐦', r: 1, c: [17], h: 'Forests, parks and suburbs', d: 'Omnivore (acorns, insects)', z: '25–35 cm',
        t: 'A bold, noisy member of the crow family that can mimic the scream of a hawk to scare rivals away from food.',
        f: 'A single jay may bury thousands of acorns in autumn, helping oak forests spread.' },
      { k: 'magpie', n: 'Magpie', s: 'Genus Pica', e: '🐦', r: 1, c: [18], h: 'Farmland, parks and towns', d: 'Omnivore', z: '44–46 cm',
        t: 'A sleek black-and-white corvid with a long, glossy tail and a famously sharp mind.',
        f: 'In 2008 Eurasian magpies became the first non-mammals shown to recognise themselves in a mirror.' },
      { k: 'bulbul', n: 'Bulbul', s: 'Family Pycnonotidae', e: '🐦', r: 1, c: [16], h: 'Gardens and scrub of Asia & Africa', d: 'Omnivore (fruit, insects)', z: '14–23 cm',
        t: 'A crested songbird with a bubbly, liquid call, common in gardens across Asia and Africa.',
        f: 'The red-vented bulbul is so adaptable it now lives on islands from Hawaii to Fiji.' },
      { k: 'brambling', n: 'Brambling', s: 'Fringilla montifringilla', e: '🐦', r: 2, c: [10], h: 'Northern forests of Europe & Asia', d: 'Omnivore (seeds, insects)', z: '16 cm',
        t: 'An orange-breasted finch that breeds in the far north and pours south in winter to feast on beech nuts.',
        f: 'Some winter roosts of bramblings hold millions of birds.' },
      { k: 'indigo-bunting', n: 'Indigo Bunting', s: 'Passerina cyanea', e: '🐦', r: 2, c: [14], h: 'Field edges of North America', d: 'Omnivore', z: '12–13 cm',
        t: 'The male looks brilliant blue, yet has no blue pigment at all — the structure of its feathers scatters light.',
        f: 'Indigo buntings migrate at night and can navigate by the stars.' },
      { k: 'hummingbird', n: 'Hummingbird', s: 'Family Trochilidae', e: '🐦', r: 2, c: [94], h: 'The Americas', d: 'Nectar and tiny insects', z: '5–22 cm',
        t: 'A hovering jewel whose wings can beat up to 80 times a second. It can even fly backwards.',
        f: 'The bee hummingbird of Cuba is the world\'s smallest bird, about 5 cm long.' },
      { k: 'snail', n: 'Snail', s: 'Class Gastropoda', e: '🐌', r: 1, c: [113], h: 'Gardens and damp places', d: 'Herbivore', z: '1–20 cm',
        t: 'A slow wanderer carrying its spiral home on its back, gliding on a ribbon of slime that protects its soft foot.',
        f: 'Snails scrape food with a tongue-like ribbon covered in thousands of microscopic teeth.' },
      { k: 'slug', n: 'Slug', s: 'Class Gastropoda', e: '🐌', r: 1, c: [114], h: 'Damp gardens and forests', d: 'Herbivore & decomposer', z: '1–30 cm',
        t: 'A snail that gave up its shell. It breathes through a hole in its side called a pneumostome.',
        f: 'Slugs have four tentacles — the upper pair carries eyes, the lower pair smells and tastes.' },
      { k: 'skunk', n: 'Skunk', s: 'Family Mephitidae', e: '🦨', r: 2, c: [361], h: 'Woodland, farms and suburbs of the Americas', d: 'Omnivore', z: '40–80 cm with tail',
        t: 'A striped stinker that warns before it sprays — stamping its feet and raising its tail. Its spray can hit a target 3 metres away.',
        f: 'People can smell skunk spray from more than a kilometre away.' },
      { k: 'porcupine', n: 'Porcupine', s: 'Families Erethizontidae & Hystricidae', e: '🦔', r: 2, c: [334], h: 'Forests and scrub', d: 'Herbivore', z: '60–90 cm',
        t: 'A slow, prickly rodent armoured with up to 30,000 quills that detach on contact and lodge in a predator\'s skin.',
        f: 'Hedgehogs look similar but aren\'t rodents at all — they\'re closer kin to shrews and moles.' },
    ],
  },
  {
    id: 'bugs', name: 'Garden Bugs', icon: '🐞', color: '#d64545',
    entries: [
      { k: 'ladybug', n: 'Ladybug', s: 'Family Coccinellidae', e: '🐞', r: 1, c: [301], h: 'Gardens and meadows', d: 'Carnivore (aphids)', z: '1–10 mm',
        t: 'A spotted beetle whose bright shell warns birds that it tastes awful. Gardeners love it as natural pest control.',
        f: 'A single ladybug can eat around 5,000 aphids in its lifetime.' },
      { k: 'bee', n: 'Bee', s: 'Clade Anthophila', e: '🐝', r: 1, c: [309], h: 'Flowers everywhere', d: 'Nectar and pollen', z: '0.2–4 cm',
        t: 'A busy pollinator. Honey bees tell their hive-mates where to find flowers by performing a "waggle dance".',
        f: 'About one in every three bites of food we eat depends on pollinators like bees.' },
      { k: 'ant', n: 'Ant', s: 'Family Formicidae', e: '🐜', r: 1, c: [310], h: 'Almost every land habitat', d: 'Omnivore', z: '1–30 mm',
        t: 'A tiny superorganism living in colonies of up to millions. Ants communicate by laying invisible trails of scent.',
        f: 'Some ants can carry 10 to 50 times their own body weight.' },
      { k: 'grasshopper', n: 'Grasshopper', s: 'Suborder Caelifera', e: '🦗', r: 1, c: [311], h: 'Grasslands and gardens', d: 'Herbivore', z: '1–11 cm',
        t: 'A powerful jumper that can leap 20 times its body length, then snap open its wings to glide away.',
        f: 'Grasshoppers hear with "ears" on their bellies, just behind their legs.' },
      { k: 'cricket', n: 'Cricket', s: 'Family Gryllidae', e: '🦗', r: 1, c: [312], h: 'Fields, gardens and houses', d: 'Omnivore', z: '0.3–5 cm',
        t: 'A night singer that chirps by rubbing a ridged file on one wing against a scraper on the other.',
        f: 'Count a snowy tree cricket\'s chirps in 13 seconds and add 40 to get the temperature in °F.' },
      { k: 'mantis', n: 'Praying Mantis', s: 'Order Mantodea', e: '🦗', r: 2, c: [315], h: 'Gardens, meadows and forests', d: 'Carnivore', z: '1–17 cm',
        t: 'An ambush hunter that waits motionless, then snatches prey with spiked forelegs faster than you can blink.',
        f: 'A mantis can swivel its head 180 degrees to look over its shoulder.' },
      { k: 'cicada', n: 'Cicada', s: 'Family Cicadidae', e: '🦗', r: 2, c: [316], h: 'Trees in warm regions', d: 'Plant sap', z: '2–5 cm',
        t: 'The loudest insect on Earth — males buzz by buckling drum-like plates called tymbals on their abdomens.',
        f: 'Periodical cicadas spend 13 or 17 years underground, then all emerge at once.' },
      { k: 'leafhopper', n: 'Leafhopper', s: 'Family Cicadellidae', e: '🦗', r: 2, c: [317], h: 'Grasses and plants', d: 'Plant sap', z: '2–15 mm',
        t: 'A tiny sap-sipper that springs away like a flea when disturbed, many dressed in dazzling stripes.',
        f: 'Leafhoppers "talk" to each other by sending vibrations through plant stems.' },
      { k: 'lacewing', n: 'Lacewing', s: 'Family Chrysopidae', e: '🦋', r: 2, c: [318], h: 'Gardens and woodland', d: 'Adults: nectar · Larvae: aphids', z: 'Wingspan 1–3 cm',
        t: 'A delicate insect with glassy, net-veined wings and golden eyes. Its larvae are fierce "aphid lions".',
        f: 'Lacewings lay each egg on top of a thin silk stalk to keep it away from hungry predators.' },
      { k: 'stick-insect', n: 'Stick Insect', s: 'Order Phasmatodea', e: '🪵', r: 2, c: [313], h: 'Tropical and temperate forests', d: 'Herbivore', z: '1.5–60 cm',
        t: 'A master of disguise that looks — and even sways — like a twig in the breeze.',
        f: 'Some stick insect species can reproduce without any males.' },
      { k: 'dragonfly', n: 'Dragonfly', s: 'Infraorder Anisoptera', e: '🪰', r: 1, c: [319], h: 'Ponds, lakes and streams', d: 'Carnivore', z: 'Wingspan 2–19 cm',
        t: 'An aerial hunter that can fly in every direction and catches most of the prey it chases.',
        f: 'Dragonfly relatives 300 million years ago had wingspans of about 70 cm.' },
      { k: 'damselfly', n: 'Damselfly', s: 'Suborder Zygoptera', e: '🪰', r: 1, c: [320], h: 'Ponds and streams', d: 'Carnivore', z: 'Body 2–5 cm',
        t: 'A slender cousin of the dragonfly that folds its wings along its back when resting.',
        f: 'Damselfly young live underwater for months, breathing through gills at the tips of their tails.' },
      { k: 'monarch', n: 'Monarch Butterfly', s: 'Danaus plexippus', e: '🦋', r: 2, c: [323], h: 'Meadows of the Americas', d: 'Nectar · Caterpillars: milkweed', z: 'Wingspan 9–10 cm',
        t: 'An orange-and-black traveller that migrates up to 4,000 km to spend the winter in Mexican mountain forests.',
        f: 'Milkweed toxins stored from its caterpillar days make the monarch poisonous to birds.' },
      { k: 'red-admiral', n: 'Red Admiral', s: 'Vanessa atalanta', e: '🦋', r: 1, c: [321], h: 'Gardens and woodland edges', d: 'Nectar, sap and rotting fruit', z: 'Wingspan 5–6.5 cm',
        t: 'A velvety black butterfly slashed with scarlet bands, often seen sipping fallen fruit in autumn.',
        f: 'Red admirals are strong migrants, flying north across Europe each spring.' },
      { k: 'ringlet', n: 'Ringlet', s: 'Aphantopus hyperantus', e: '🦋', r: 2, c: [322], h: 'Grassy meadows and hedgerows', d: 'Nectar', z: 'Wingspan 4–5 cm',
        t: 'A dusky brown butterfly decorated with yellow-ringed eyespots. It keeps flying even on cloudy days.',
        f: 'Ringlet females scatter their eggs while flying over grass instead of placing them on leaves.' },
      { k: 'cabbage-white', n: 'Cabbage White', s: 'Pieris rapae', e: '🦋', r: 1, c: [324], h: 'Gardens and farmland', d: 'Nectar · Caterpillars: cabbage', z: 'Wingspan 4.5–6.5 cm',
        t: 'A common white butterfly with dark wingtips, whose green caterpillars munch cabbage and broccoli.',
        f: 'Originally European, it hitched rides with people to North America, Australia and New Zealand.' },
      { k: 'sulphur', n: 'Sulphur Butterfly', s: 'Subfamily Coliadinae', e: '🦋', r: 1, c: [325], h: 'Open fields worldwide', d: 'Nectar', z: 'Wingspan 3–7 cm',
        t: 'A sunshine-yellow butterfly that often gathers in groups at puddles to sip minerals.',
        f: 'The word "butterfly" may come from butter-yellow species like these.' },
      { k: 'blue-butterfly', n: 'Blue Butterfly', s: 'Family Lycaenidae', e: '🦋', r: 1, c: [326], h: 'Meadows and grasslands', d: 'Nectar', z: 'Wingspan 1.5–5 cm',
        t: 'A tiny butterfly with shimmering wings. Many of its caterpillars are guarded by ants in exchange for sweet droplets.',
        f: 'Large blue caterpillars trick ants into carrying them into their nest — then eat the ant grubs.' },
    ],
  },
  {
    id: 'crawlies', name: 'Creepy Crawlies', icon: '🕷️', color: '#6b5b95',
    entries: [
      { k: 'orb-weaver', n: 'Orb Weaver', s: 'Family Araneidae', e: '🕷️', r: 1, c: [72, 73, 74], h: 'Gardens, fields and forests', d: 'Carnivore', z: 'Body 0.5–3 cm',
        t: 'The architect of the classic wheel-shaped web. Many orb weavers eat their web each night and spin a fresh one.',
        f: 'Weight for weight, spider silk is stronger than steel.' },
      { k: 'black-widow', n: 'Black Widow', s: 'Latrodectus mactans', e: '🕷️', r: 2, c: [75], h: 'Dark corners and woodpiles', d: 'Carnivore', z: 'Body 0.8–1.3 cm',
        t: 'A glossy black spider with a red hourglass on its belly. Drop for drop, its venom is stronger than a rattlesnake\'s.',
        f: 'Despite its reputation, bites are rare, and deaths are very rare with modern medical care.' },
      { k: 'tarantula', n: 'Tarantula', s: 'Family Theraphosidae', e: '🕷️', r: 2, c: [76], h: 'Deserts and rainforests', d: 'Carnivore', z: 'Leg span up to 28 cm',
        t: 'A huge, hairy spider that hunts on the ground at night. Some flick barbed hairs from their abdomen at attackers.',
        f: 'Female tarantulas of some species live for 30 years or more.' },
      { k: 'wolf-spider', n: 'Wolf Spider', s: 'Family Lycosidae', e: '🕷️', r: 1, c: [77], h: 'Grass, gardens and leaf litter', d: 'Carnivore', z: 'Body 0.5–3.5 cm',
        t: 'A web-less hunter that runs down its prey. Mothers carry their spiderlings piled on their backs.',
        f: 'Sweep a torch across a lawn at night and wolf spider eyes glitter back like tiny diamonds.' },
      { k: 'harvestman', n: 'Harvestman', s: 'Order Opiliones', e: '🕷️', r: 1, c: [70], h: 'Gardens and forests', d: 'Omnivore', z: 'Body 1–7 mm; legs far longer',
        t: 'Often mistaken for a spider, this "daddy longlegs" has one fused body, two eyes, and no silk or venom.',
        f: 'If grabbed, a harvestman can shed a leg, which keeps twitching to distract the attacker.' },
      { k: 'tick', n: 'Tick', s: 'Order Ixodida', e: '🕷️', r: 1, c: [78], h: 'Long grass and woodland', d: 'Blood', z: '1–5 mm; balloons when fed',
        t: 'A tiny eight-legged hitchhiker that waits on grass tips with its front legs outstretched — a behaviour called "questing".',
        f: 'A feeding female tick can swell to about 100 times her unfed weight.' },
      { k: 'centipede', n: 'Centipede', s: 'Class Chilopoda', e: '🐛', r: 1, c: [79], h: 'Soil, leaf litter and rocks', d: 'Carnivore', z: '0.4–30 cm',
        t: 'A fast-running hunter that injects venom through a pair of modified front legs called forcipules.',
        f: 'No centipede has exactly 100 legs — they always have an odd number of leg pairs.' },
      { k: 'tiger-beetle', n: 'Tiger Beetle', s: 'Subfamily Cicindelinae', e: '🪲', r: 2, c: [300], h: 'Sandy shores and paths', d: 'Carnivore', z: '0.6–4 cm',
        t: 'One of the fastest runners for its size — so quick that it briefly goes blind while chasing prey.',
        f: 'Scaled up to human size, a tiger beetle would sprint at hundreds of kilometres per hour.' },
      { k: 'ground-beetle', n: 'Ground Beetle', s: 'Family Carabidae', e: '🪲', r: 1, c: [302], h: 'Soil and leaf litter', d: 'Carnivore', z: '1–60 mm',
        t: 'A shiny night patroller that hunts slugs and caterpillars. There are over 40,000 kinds.',
        f: 'Bombardier beetles, a type of ground beetle, fire a boiling chemical spray from their rear.' },
      { k: 'longhorn-beetle', n: 'Longhorn Beetle', s: 'Family Cerambycidae', e: '🪲', r: 2, c: [303], h: 'Forests and woodland', d: 'Herbivore (wood, plants)', z: '0.2–17 cm',
        t: 'Named for its extraordinarily long antennae, sometimes several times the length of its body.',
        f: 'Its larvae bore through wood for years before emerging as adults.' },
      { k: 'leaf-beetle', n: 'Leaf Beetle', s: 'Family Chrysomelidae', e: '🪲', r: 1, c: [304], h: 'Gardens, crops and meadows', d: 'Herbivore', z: 'Mostly under 12 mm',
        t: 'A small, often metallic beetle that munches leaves. The Colorado potato beetle is its most infamous member.',
        f: 'Golden tortoise beetles, a kind of leaf beetle, can change from gold to red in minutes.' },
      { k: 'dung-beetle', n: 'Dung Beetle', s: 'Subfamily Scarabaeinae', e: '🪲', r: 2, c: [305], h: 'Grasslands, farms and deserts', d: 'Dung', z: '0.5–6 cm',
        t: 'A tireless recycler that rolls balls of dung many times its own weight to feed its young.',
        f: 'Some dung beetles steer at night using the glow of the Milky Way.' },
      { k: 'rhino-beetle', n: 'Rhinoceros Beetle', s: 'Subfamily Dynastinae', e: '🪲', r: 3, c: [306], h: 'Tropical and temperate forests', d: 'Herbivore (sap, fruit)', z: '2–17 cm',
        t: 'A horned heavyweight that uses its horn to flip rivals off branches in battles over mates.',
        f: 'For their size, rhinoceros beetles are among the strongest animals on the planet.' },
      { k: 'weevil', n: 'Weevil', s: 'Superfamily Curculionoidea', e: '🪲', r: 1, c: [307], h: 'Plants, crops and pantries', d: 'Herbivore', z: 'Mostly 3–10 mm',
        t: 'A beetle with a long snout tipped with tiny jaws, used to bore into seeds, nuts and grain.',
        f: 'With tens of thousands of species, weevils form one of the largest animal families on Earth.' },
      { k: 'roundworm', n: 'Roundworm', s: 'Phylum Nematoda', e: '🪱', r: 3, c: [111], h: 'Soil, water — everywhere', d: 'Bacteria, plants or hosts', z: '0.1 mm – 8 m',
        t: 'A mostly microscopic worm so abundant that around four of every five animals on Earth may be nematodes.',
        f: 'The nematode C. elegans was the first animal to have its whole genome sequenced.' },
      { k: 'isopod', n: 'Isopod', s: 'Order Isopoda', e: '🐛', r: 1, c: [126], h: 'Damp logs and gardens; sea floors', d: 'Detritivore', z: '0.3 mm – 50 cm',
        t: 'A crustacean that moved onto land. Pill bugs roll into armoured balls when threatened.',
        f: 'The giant isopod of the deep sea grows to about 50 cm and can survive years without food in captivity.' },
    ],
  },
  {
    id: 'wetlands', name: 'Wetland Birds', icon: '🦩', color: '#e07a9b',
    entries: [
      { k: 'flamingo', n: 'Flamingo', s: 'Family Phoenicopteridae', e: '🦩', r: 2, c: [130], h: 'Salt lakes and lagoons', d: 'Filter feeder', z: '0.8–1.5 m tall',
        t: 'A leggy wader that feeds upside-down, filtering tiny shrimp and algae through its beak.',
        f: 'Flamingos hatch grey — their pink colour comes from pigments in their food.' },
      { k: 'pelican', n: 'Pelican', s: 'Genus Pelecanus', e: '🐦', r: 2, c: [144], h: 'Coasts, lakes and rivers', d: 'Fish', z: '1–1.8 m long',
        t: 'A big-billed fisher whose stretchy throat pouch can scoop up more water than its stomach can hold.',
        f: 'Brown pelicans plunge-dive headfirst from heights of up to 20 metres to catch fish.' },
      { k: 'white-stork', n: 'White Stork', s: 'Ciconia ciconia', e: '🐦', r: 2, c: [127], h: 'Farmland and wetlands of Europe & Africa', d: 'Carnivore', z: '1–1.15 m tall',
        t: 'A tall bird famous in folklore for delivering babies. It builds huge nests on rooftops and chimneys.',
        f: 'Nearly voiceless, white storks "talk" by loudly clattering their bills.' },
      { k: 'black-stork', n: 'Black Stork', s: 'Ciconia nigra', e: '🐦', r: 3, c: [128], h: 'Remote forests and wetlands', d: 'Carnivore', z: '95–100 cm',
        t: 'A shy, glossy-black stork with a red bill that hides in deep forests, unlike its rooftop-loving cousin.',
        f: 'Its black feathers shimmer purple and green in the sunlight.' },
      { k: 'spoonbill', n: 'Spoonbill', s: 'Genus Platalea', e: '🐦', r: 2, c: [129], h: 'Marshes and mudflats', d: 'Carnivore', z: '70–95 cm',
        t: 'A wader with a flat, spoon-shaped bill that it sweeps side to side through water to snap up prey by touch.',
        f: 'The roseate spoonbill gets its pink colour the same way flamingos do — from its food.' },
      { k: 'little-blue-heron', n: 'Little Blue Heron', s: 'Egretta caerulea', e: '🐦', r: 2, c: [131], h: 'Marshes of the Americas', d: 'Carnivore', z: '60–74 cm',
        t: 'A slate-blue heron that stalks slowly through the shallows. Strangely, its young are pure white for their first year.',
        f: 'White youngsters often mix into flocks of snowy egrets, which may help protect them.' },
      { k: 'great-egret', n: 'Great Egret', s: 'Ardea alba', e: '🐦', r: 1, c: [132], h: 'Wetlands worldwide', d: 'Carnivore', z: '80–104 cm',
        t: 'An elegant all-white heron that stands still as a statue before spearing fish with its dagger bill.',
        f: 'Its lacy plumes were so prized for hats that it was nearly wiped out, sparking early bird-protection laws.' },
      { k: 'bittern', n: 'Bittern', s: 'Subfamily Botaurinae', e: '🐦', r: 3, c: [133], h: 'Reedbeds and marshes', d: 'Carnivore', z: '60–80 cm',
        t: 'A camouflaged heron that points its bill skyward and sways with the reeds to vanish from sight.',
        f: 'The male Eurasian bittern\'s booming call can carry up to 5 km.' },
      { k: 'crane', n: 'Crane', s: 'Family Gruidae', e: '🐦', r: 2, c: [134], h: 'Wetlands and grasslands', d: 'Omnivore', z: '0.9–1.8 m tall',
        t: 'A towering bird whose pairs perform elaborate leaping, bowing dances. Many species mate for life.',
        f: 'In Japan, folding 1,000 paper cranes is said to grant a wish.' },
      { k: 'limpkin', n: 'Limpkin', s: 'Aramus guarauna', e: '🐦', r: 3, c: [135], h: 'Swamps of the Americas', d: 'Snails', z: '64–73 cm',
        t: 'A wading bird that feeds almost entirely on apple snails, using a slightly twisted bill to pry out the meat.',
        f: 'Its haunting, wailing scream earned it the nickname "crying bird".' },
      { k: 'sandpiper', n: 'Sandpiper', s: 'Family Scolopacidae', e: '🐦', r: 1, c: [139, 140, 141, 142], h: 'Beaches and mudflats', d: 'Carnivore', z: '18–30 cm',
        t: 'A busy shorebird that races the waves, probing the sand with its bill for worms and tiny crabs.',
        f: 'The bar-tailed godwit, a sandpiper relative, flies over 11,000 km nonstop on migration.' },
      { k: 'oystercatcher', n: 'Oystercatcher', s: 'Genus Haematopus', e: '🐦', r: 2, c: [143], h: 'Rocky and sandy coasts', d: 'Shellfish', z: '40–50 cm',
        t: 'A noisy black-and-white shorebird with a carrot-orange bill for hammering or stabbing open shellfish.',
        f: 'Young oystercatchers learn their parents\' shell-opening technique — hammering or stabbing.' },
    ],
  },
  {
    id: 'rivers', name: 'Rivers & Lakes', icon: '🏞️', color: '#2a9d8f',
    entries: [
      { k: 'tench', n: 'Tench', s: 'Tinca tinca', e: '🐟', r: 2, c: [0], h: 'Slow rivers and ponds of Europe', d: 'Omnivore', z: '20–70 cm',
        t: 'An olive-green, red-eyed fish of weedy ponds. Its tiny scales are wrapped in thick slime.',
        f: 'Folklore called it the "doctor fish", claiming its slime could heal other fish.' },
      { k: 'coho-salmon', n: 'Coho Salmon', s: 'Oncorhynchus kisutch', e: '🐟', r: 2, c: [391], h: 'North Pacific and its rivers', d: 'Carnivore', z: '50–70 cm',
        t: 'A silver ocean fish that returns to the very stream where it hatched to spawn, turning red as it goes.',
        f: 'Salmon find their home river by remembering the smell of its water.' },
      { k: 'sturgeon', n: 'Sturgeon', s: 'Family Acipenseridae', e: '🐟', r: 3, c: [394], h: 'Large rivers, lakes and coasts', d: 'Bottom-feeder', z: '0.7–7 m',
        t: 'An armoured "living fossil" whose lineage dates back to the dinosaurs. It vacuums food from riverbeds with toothless lips.',
        f: 'The beluga sturgeon can live over 100 years and weigh more than a tonne.' },
      { k: 'gar', n: 'Gar', s: 'Family Lepisosteidae', e: '🐟', r: 3, c: [395], h: 'Rivers and swamps of North America', d: 'Fish', z: '0.6–3 m',
        t: 'A long, needle-toothed ambusher armoured in diamond-shaped scales once used by Native Americans as arrowheads.',
        f: 'Gars can gulp air, letting them survive in warm, oxygen-poor water.' },
      { k: 'crayfish', n: 'Crayfish', s: 'Infraorder Astacidea', e: '🦞', r: 2, c: [124], h: 'Streams, ponds and lakes', d: 'Omnivore', z: '2–40 cm',
        t: 'A freshwater cousin of the lobster that shoots backwards with a flick of its tail when startled.',
        f: 'Crayfish can regrow lost claws and legs when they moult.' },
      { k: 'beaver', n: 'Beaver', s: 'Genus Castor', e: '🦫', r: 2, c: [337], h: 'Rivers and ponds of North America & Eurasia', d: 'Herbivore (bark, plants)', z: '1–1.3 m with tail',
        t: 'Nature\'s engineer, felling trees with iron-strengthened orange teeth to build dams and lodges.',
        f: 'Beaver ponds create wetlands that support hundreds of other species.' },
      { k: 'otter', n: 'Otter', s: 'Subfamily Lutrinae', e: '🦦', r: 2, c: [360], h: 'Rivers, lakes and coasts', d: 'Carnivore (fish, shellfish)', z: '0.6–1.8 m',
        t: 'A sleek, playful swimmer that closes its ears and nostrils underwater. Sea otters hold paws while sleeping so they don\'t drift apart.',
        f: 'Sea otters have the densest fur of any animal — up to about 150,000 hairs per square centimetre.' },
      { k: 'mink', n: 'Mink', s: 'Neogale vison & Mustela lutreola', e: '🦦', r: 2, c: [357], h: 'Riverbanks and marshes', d: 'Carnivore', z: '45–70 cm with tail',
        t: 'A sleek, semi-aquatic hunter with oily, waterproof fur, equally at home chasing fish or rabbits.',
        f: 'American mink that escaped from fur farms now live wild across much of Europe.' },
      { k: 'merganser', n: 'Red-breasted Merganser', s: 'Mergus serrator', e: '🦆', r: 2, c: [98], h: 'Coasts and northern lakes', d: 'Fish', z: '51–64 cm',
        t: 'A diving duck with a shaggy crest and a thin, saw-toothed bill for gripping slippery fish.',
        f: 'Its serrated bill gives mergansers the nickname "sawbills".' },
      { k: 'coot', n: 'American Coot', s: 'Fulica americana', e: '🐦', r: 1, c: [137], h: 'Ponds and marshes of the Americas', d: 'Omnivore', z: '34–43 cm',
        t: 'A dark, chicken-like water bird with a white bill. Its lobed toes work as paddles in water and snowshoes on mud.',
        f: 'Coots aren\'t ducks at all — they\'re related to rails and cranes.' },
      { k: 'swamphen', n: 'Purple Swamphen', s: 'Porphyrio porphyrio', e: '🐦', r: 2, c: [136], h: 'Reedy marshes of Europe, Africa & Asia', d: 'Omnivore', z: '38–50 cm',
        t: 'A glossy purple-blue marsh bird with a red forehead shield and oversized feet for walking on floating plants.',
        f: 'It holds food up to its bill with one foot, almost like a parrot.' },
    ],
  },
  {
    id: 'herps', name: 'Scales & Slime', icon: '🦎', color: '#6a994e',
    entries: [
      { k: 'bullfrog', n: 'Bullfrog', s: 'Lithobates catesbeianus', e: '🐸', r: 1, c: [30], h: 'Ponds and lakes', d: 'Carnivore', z: '9–20 cm',
        t: 'A giant frog with a deep, cow-like "jug-o-rum" call. It eats almost anything it can fit in its mouth — even snakes.',
        f: 'In male bullfrogs, the eardrum is bigger than the eye.' },
      { k: 'tree-frog', n: 'Tree Frog', s: 'Family Hylidae', e: '🐸', r: 1, c: [31], h: 'Trees and shrubs near water', d: 'Insects', z: '1.5–14 cm',
        t: 'A climbing frog with sticky toe pads that let it cling to leaves — and even glass.',
        f: 'Some tree frogs can shift colour from green to brown to match their surroundings.' },
      { k: 'tailed-frog', n: 'Tailed Frog', s: 'Ascaphus truei', e: '🐸', r: 3, c: [32], h: 'Cold mountain streams of NW North America', d: 'Carnivore', z: '2.5–5 cm',
        t: 'A small frog of icy, rushing streams. It has no eardrums and no croak — useless over the roar of water.',
        f: 'The "tail" is found only on males and is used in mating, a feature unique among frogs.' },
      { k: 'fire-salamander', n: 'Fire Salamander', s: 'Salamandra salamandra', e: '🦎', r: 2, c: [25], h: 'Damp European forests', d: 'Carnivore', z: '15–25 cm',
        t: 'A black-and-yellow salamander whose bright colours warn of toxic skin secretions.',
        f: 'Its name comes from legends of salamanders crawling out of burning logs — they had been hiding inside.' },
      { k: 'newt', n: 'Newt', s: 'Subfamily Pleurodelinae', e: '🦎', r: 1, c: [26, 27], h: 'Ponds and damp woodland', d: 'Carnivore', z: '7–20 cm',
        t: 'A small salamander that returns to ponds to breed. Young of some species live on land as bright orange "efts".',
        f: 'Newts can regrow lost legs, tails, parts of their eyes and even heart tissue.' },
      { k: 'spotted-salamander', n: 'Spotted Salamander', s: 'Ambystoma maculatum', e: '🦎', r: 2, c: [28], h: 'Forests of eastern North America', d: 'Carnivore', z: '15–25 cm',
        t: 'A black salamander with yellow polka dots that emerges in great numbers on rainy spring nights to breed.',
        f: 'Algae live inside its eggs — and even its cells — making it partly solar-powered.' },
      { k: 'axolotl', n: 'Axolotl', s: 'Ambystoma mexicanum', e: '🦎', r: 3, c: [29], h: 'Lake Xochimilco, Mexico', d: 'Carnivore', z: '15–30 cm',
        t: 'A smiling salamander that never grows up, keeping its feathery gills and living underwater its whole life.',
        f: 'Critically endangered in the wild, axolotls can regrow limbs, spinal cord and even parts of the brain.' },
      { k: 'pond-turtle', n: 'Pond Turtle', s: 'Freshwater turtles', e: '🐢', r: 1, c: [35, 36], h: 'Ponds, rivers and marshes', d: 'Omnivore', z: 'Shell 8–30 cm',
        t: 'A sun-loving turtle that basks on logs to warm up, then plops into the water at the first sign of danger.',
        f: 'Some turtles overwinter underwater, absorbing oxygen through their skin and rear end.' },
      { k: 'box-turtle', n: 'Box Turtle', s: 'Genus Terrapene', e: '🐢', r: 2, c: [37], h: 'Woodland and meadows', d: 'Omnivore', z: 'Shell 11–20 cm',
        t: 'A land turtle with a hinged lower shell that closes up tight like a box.',
        f: 'Box turtles can live for more than 100 years.' },
      { k: 'gecko', n: 'Gecko', s: 'Infraorder Gekkota', e: '🦎', r: 1, c: [38], h: 'Warm climates; house walls', d: 'Insects', z: '2–35 cm',
        t: 'A wall-walking lizard whose toes carry millions of microscopic hairs that grip almost any surface.',
        f: 'Most geckos can\'t blink — they lick their eyes to keep them clean.' },
      { k: 'iguana', n: 'Green Iguana', s: 'Iguana iguana', e: '🦎', r: 2, c: [39], h: 'Tropical forests of the Americas', d: 'Herbivore', z: '1.2–2 m with tail',
        t: 'A big green lizard with a spiny crest that basks in treetops and drops into rivers to escape danger.',
        f: 'Iguanas have a light-sensing "third eye" on top of their heads.' },
      { k: 'anole', n: 'Anole', s: 'Anolis carolinensis', e: '🦎', r: 1, c: [40], h: 'Trees and gardens of the SE USA & Caribbean', d: 'Insects', z: '12–20 cm',
        t: 'A small lizard that flashes a pink throat fan called a dewlap to claim territory. It can shift from green to brown.',
        f: 'Anoles are nicknamed "American chameleons", but they aren\'t chameleons at all.' },
      { k: 'whiptail', n: 'Whiptail', s: 'Family Teiidae', e: '🦎', r: 2, c: [41], h: 'Deserts and grasslands of the Americas', d: 'Insects', z: '15–30 cm',
        t: 'A fast, restless lizard with a long whip-like tail, constantly on the move hunting insects.',
        f: 'Some whiptail species are all-female and reproduce by cloning.' },
      { k: 'agama', n: 'Agama', s: 'Family Agamidae', e: '🦎', r: 2, c: [42], h: 'Rocky areas of Africa & Asia', d: 'Insects', z: '12–30 cm',
        t: 'A sun-loving rock lizard. The male rainbow agama flaunts a fiery orange head and electric-blue body.',
        f: 'Male agamas bob their heads like push-ups to impress females and warn rivals.' },
      { k: 'alligator-lizard', n: 'Alligator Lizard', s: 'Family Anguidae', e: '🦎', r: 2, c: [44], h: 'Woodland of western North America', d: 'Carnivore', z: '25–43 cm',
        t: 'A stiff-scaled lizard with a long body and short legs, named for its alligator-like armour.',
        f: 'A soft fold of skin along each side lets its armoured body expand when it eats or breathes.' },
      { k: 'green-lizard', n: 'Green Lizard', s: 'Lacerta viridis', e: '🦎', r: 2, c: [46], h: 'Sunny hedges of Europe', d: 'Carnivore', z: '30–40 cm',
        t: 'A brilliant emerald lizard of European meadows. In spring, the males\' throats turn vivid blue.',
        f: 'Like many lizards, it can drop its tail to escape a predator and grow it back.' },
      { k: 'chameleon', n: 'Chameleon', s: 'Family Chamaeleonidae', e: '🦎', r: 3, c: [47], h: 'Africa, Madagascar & southern Europe', d: 'Insects', z: '2–70 cm',
        t: 'A slow-motion lizard with swivelling eyes that look two ways at once, and a tongue that shoots out faster than a blink.',
        f: 'Chameleons change colour mainly to communicate and control temperature, not just to hide.' },
      { k: 'komodo', n: 'Komodo Dragon', s: 'Varanus komodoensis', e: '🦎', r: 3, c: [48], h: 'Indonesian islands', d: 'Carnivore', z: '2–3 m',
        t: 'The largest living lizard, a powerful ambush hunter with a venomous bite.',
        f: 'Female Komodo dragons can lay fertile eggs without a male.' },
      { k: 'nile-crocodile', n: 'Nile Crocodile', s: 'Crocodylus niloticus', e: '🐊', r: 3, c: [49], h: 'Rivers and lakes of Africa', d: 'Carnivore', z: '3.5–5 m',
        t: 'An armoured river giant that lurks with only its eyes and nostrils above the water.',
        f: 'Crocodile mothers gently carry their hatchlings to the water in their huge jaws.' },
      { k: 'alligator', n: 'American Alligator', s: 'Alligator mississippiensis', e: '🐊', r: 2, c: [50], h: 'Swamps of the SE United States', d: 'Carnivore', z: '2.6–4.6 m',
        t: 'A broad-snouted swamp king that bellows so deeply the water dances on its back.',
        f: 'The temperature of the nest decides whether hatchlings are male or female.' },
    ],
  },
  {
    id: 'snakes', name: 'Snakes', icon: '🐍', color: '#8a9a3b',
    entries: [
      { k: 'worm-snake', n: 'Worm Snake', s: 'Carphophis amoenus', e: '🐍', r: 3, c: [52], h: 'Moist forests of the eastern USA', d: 'Earthworms', z: '19–28 cm',
        t: 'A tiny, glossy snake that burrows like an earthworm and pokes with its pointed tail if picked up.',
        f: 'Harmless to people, it spends most of its life hidden under logs and in soil.' },
      { k: 'ringneck-snake', n: 'Ringneck Snake', s: 'Diadophis punctatus', e: '🐍', r: 2, c: [53], h: 'Woodland of North America', d: 'Carnivore', z: '25–38 cm',
        t: 'A slender snake with a golden collar that curls its tail to flash a red-orange belly when threatened.',
        f: 'It is mildly venomous to its small prey but harmless to people.' },
      { k: 'hognose-snake', n: 'Hognose Snake', s: 'Genus Heterodon', e: '🐍', r: 2, c: [54], h: 'Sandy areas of North America', d: 'Toads', z: '40–100 cm',
        t: 'A dramatic actor that flattens its neck and hisses like a cobra — and if that fails, rolls over and plays dead.',
        f: 'Its upturned snout works like a shovel for digging up toads.' },
      { k: 'green-snake', n: 'Green Snake', s: 'Genus Opheodrys', e: '🐍', r: 2, c: [55], h: 'Meadows and shrubs', d: 'Insects', z: '35–110 cm',
        t: 'A slender, leaf-green snake that vanishes into grass and vines while hunting crickets and caterpillars.',
        f: 'It is one of the few snakes that eats mostly insects.' },
      { k: 'kingsnake', n: 'Kingsnake', s: 'Genus Lampropeltis', e: '🐍', r: 2, c: [56], h: 'Varied habitats of the Americas', d: 'Carnivore', z: '0.6–1.8 m',
        t: 'A powerful constrictor named "king" because it eats other snakes — including venomous rattlesnakes.',
        f: 'Kingsnakes are largely resistant to rattlesnake venom.' },
      { k: 'garter-snake', n: 'Garter Snake', s: 'Genus Thamnophis', e: '🐍', r: 1, c: [57], h: 'Gardens, meadows and wetlands', d: 'Carnivore', z: '45–135 cm',
        t: 'One of the most common snakes in North America, striped like old-fashioned sock garters.',
        f: 'Each spring tens of thousands emerge together from the Narcisse snake dens in Manitoba, Canada.' },
      { k: 'water-snake', n: 'Water Snake', s: 'Genus Nerodia', e: '🐍', r: 2, c: [58], h: 'Rivers, lakes and marshes', d: 'Fish and frogs', z: '60–150 cm',
        t: 'A thick-bodied swimmer often mistaken for the venomous cottonmouth, though it is harmless.',
        f: 'Water snakes give birth to live young — sometimes dozens at once.' },
      { k: 'vine-snake', n: 'Vine Snake', s: 'Genera Oxybelis & Ahaetulla', e: '🐍', r: 3, c: [59], h: 'Tropical forests', d: 'Lizards and frogs', z: '1–2 m',
        t: 'A whip-thin snake that looks exactly like a hanging vine as it waits for lizards to pass.',
        f: 'Asian vine snakes have grooves on their snouts that let them see forward in 3D to strike accurately.' },
      { k: 'night-snake', n: 'Night Snake', s: 'Hypsiglena torquata', e: '🐍', r: 3, c: [60], h: 'Deserts and scrub of western North America', d: 'Lizards', z: '30–66 cm',
        t: 'A small, spotted snake with cat-like vertical pupils that hunts sleeping lizards after dark.',
        f: 'Its mild venom, delivered by rear fangs, is harmless to humans.' },
      { k: 'boa', n: 'Boa Constrictor', s: 'Boa constrictor', e: '🐍', r: 3, c: [61], h: 'Tropical Americas', d: 'Carnivore', z: '1–4 m',
        t: 'A heavy-bodied constrictor that tightens its coils each time its prey breathes out, stopping blood flow.',
        f: 'Boas give birth to live young, sometimes more than 60 at a time.' },
      { k: 'rock-python', n: 'Rock Python', s: 'Python sebae', e: '🐍', r: 3, c: [62], h: 'Savannas and forests of Africa', d: 'Carnivore', z: '3–6 m',
        t: 'Africa\'s largest snake, strong enough to swallow an antelope whole.',
        f: 'Mother pythons coil around their eggs to guard them until they hatch.' },
      { k: 'indian-cobra', n: 'Indian Cobra', s: 'Naja naja', e: '🐍', r: 3, c: [63], h: 'Fields and forests of South Asia', d: 'Carnivore', z: '1–1.5 m',
        t: 'A hooded snake that rears up and spreads its neck ribs when threatened, showing the famous "spectacle" mark.',
        f: 'It is one of India\'s "Big Four" snakes responsible for most snakebites there.' },
      { k: 'green-mamba', n: 'Green Mamba', s: 'Genus Dendroaspis', e: '🐍', r: 3, c: [64], h: 'Forests of East & Southern Africa', d: 'Carnivore', z: '1.8–2.5 m',
        t: 'A shy, emerald tree snake that glides among the branches. Its bite is dangerously venomous.',
        f: 'Unlike its cousin the black mamba, it usually flees rather than confronting people.' },
      { k: 'diamondback', n: 'Diamondback Rattlesnake', s: 'Crotalus adamanteus', e: '🐍', r: 3, c: [67], h: 'Pinewoods of the SE United States', d: 'Carnivore', z: '1–2 m',
        t: 'The heaviest venomous snake in the Americas, warning intruders with the dry buzz of its rattle.',
        f: 'A new rattle segment is added each time it sheds its skin.' },
    ],
  },
  {
    id: 'ocean', name: 'Ocean Giants', icon: '🐋', color: '#1d4e89',
    entries: [
      { k: 'great-white', n: 'Great White Shark', s: 'Carcharodon carcharias', e: '🦈', r: 3, c: [2], h: 'Cool coastal oceans', d: 'Carnivore', z: '4–6 m',
        t: 'The ocean\'s most famous predator. Jelly-filled pores on its snout sense the faint electric fields of hidden prey.',
        f: 'Great whites sometimes leap completely out of the water to ambush seals.' },
      { k: 'tiger-shark', n: 'Tiger Shark', s: 'Galeocerdo cuvier', e: '🦈', r: 3, c: [3], h: 'Tropical and warm seas', d: 'Almost anything', z: '3–5 m',
        t: 'A striped "garbage can of the sea" — turtles, birds and even licence plates have been found in its stomach.',
        f: 'Its stripes fade as it grows older.' },
      { k: 'hammerhead', n: 'Hammerhead Shark', s: 'Genus Sphyrna', e: '🦈', r: 3, c: [4], h: 'Warm coastal seas', d: 'Carnivore', z: '0.9–6 m',
        t: 'A shark with a wide, hammer-shaped head that sweeps the sand like a metal detector for buried stingrays.',
        f: 'Its wide-set eyes give it an excellent all-round view.' },
      { k: 'electric-ray', n: 'Electric Ray', s: 'Order Torpediniformes', e: '🐟', r: 3, c: [5], h: 'Sandy sea floors', d: 'Carnivore', z: '0.3–1.8 m',
        t: 'A soft, round ray that stuns prey with electric shocks of up to 220 volts.',
        f: 'Ancient Greeks and Romans used electric rays to numb pain.' },
      { k: 'stingray', n: 'Stingray', s: 'Order Myliobatiformes', e: '🐟', r: 2, c: [6], h: 'Shallow coastal waters', d: 'Carnivore', z: '0.3–2 m wide',
        t: 'A flat fish that buries itself in sand with only its eyes poking out. The venomous barb on its tail is for defence only.',
        f: 'Shuffle your feet when wading — stingrays feel the vibration and glide away.' },
      { k: 'loggerhead', n: 'Loggerhead Turtle', s: 'Caretta caretta', e: '🐢', r: 3, c: [33], h: 'Oceans worldwide', d: 'Carnivore', z: 'Shell ~90 cm',
        t: 'A big-headed sea turtle whose powerful jaws crush crabs and conchs. It crosses entire oceans in its lifetime.',
        f: 'Hatchlings use Earth\'s magnetic field like a built-in map.' },
      { k: 'leatherback', n: 'Leatherback Turtle', s: 'Dermochelys coriacea', e: '🐢', r: 3, c: [34], h: 'Open oceans worldwide', d: 'Jellyfish', z: '1.5–2 m',
        t: 'The largest turtle on Earth, with a rubbery, ridged shell instead of hard plates. It dives deeper than 1,000 metres.',
        f: 'Its throat is lined with backward-pointing spines that stop slippery jellyfish escaping.' },
      { k: 'sea-snake', n: 'Sea Snake', s: 'Subfamily Hydrophiinae', e: '🐍', r: 3, c: [65], h: 'Warm Indian & Pacific Oceans', d: 'Fish and eels', z: '0.5–3 m',
        t: 'A snake fully adapted to life at sea, with a paddle-shaped tail for swimming. Many are highly venomous.',
        f: 'Some sea snakes absorb oxygen through their skin, allowing very long dives.' },
      { k: 'orca', n: 'Orca', s: 'Orcinus orca', e: '🐋', r: 3, c: [148], h: 'All oceans', d: 'Carnivore', z: '5–9 m',
        t: 'The largest dolphin, a black-and-white hunter living in close family pods that each have their own "dialect".',
        f: 'Orcas are apex predators that even hunt great white sharks.' },
      { k: 'grey-whale', n: 'Grey Whale', s: 'Eschrichtius robustus', e: '🐋', r: 3, c: [147], h: 'North Pacific coasts', d: 'Filter feeder', z: '12–15 m',
        t: 'A barnacle-crusted giant that rolls on its side to suck up mud and filter out tiny crustaceans.',
        f: 'It makes one of the longest migrations of any mammal — up to 20,000 km round trip.' },
      { k: 'dugong', n: 'Dugong', s: 'Dugong dugon', e: '🦭', r: 3, c: [149], h: 'Warm coastal seagrass beds', d: 'Seagrass', z: '2.5–3 m',
        t: 'A gentle "sea cow" that grazes on seagrass meadows. Sailors\' sightings may have inspired mermaid legends.',
        f: 'Dugongs are more closely related to elephants than to whales or seals.' },
      { k: 'sea-lion', n: 'Sea Lion', s: 'Subfamily Otariinae', e: '🦭', r: 2, c: [150], h: 'Pacific & Southern Ocean coasts', d: 'Carnivore', z: '1.5–3.3 m',
        t: 'A barking, playful swimmer that "walks" on land by turning its rear flippers forward — something true seals can\'t do.',
        f: 'Sea lions have visible ear flaps; true seals just have ear holes.' },
      { k: 'albatross', n: 'Albatross', s: 'Family Diomedeidae', e: '🐦', r: 3, c: [146], h: 'Southern Ocean & North Pacific', d: 'Squid and fish', z: 'Wingspan 2–3.5 m',
        t: 'A master glider with the largest wingspan of any living bird, able to soar for hours without flapping.',
        f: 'Wisdom, a Laysan albatross, was still laying eggs past the age of 70.' },
      { k: 'barracouta', n: 'Barracouta', s: 'Thyrsites atun', e: '🐟', r: 2, c: [389], h: 'Cool Southern Hemisphere seas', d: 'Carnivore', z: 'Usually ~75 cm',
        t: 'A long, silvery predator with fang-like teeth, known as snoek in South Africa.',
        f: 'It is often confused with the barracuda, but the two aren\'t closely related.' },
      { k: 'eel', n: 'Eel', s: 'Order Anguilliformes', e: '🐍', r: 2, c: [390], h: 'Rivers and oceans', d: 'Carnivore', z: '0.1–4 m',
        t: 'A snake-shaped fish that can wriggle short distances over wet land. European eels cross the Atlantic to breed.',
        f: 'No one has ever watched European eels spawn in the wild — it remains a mystery.' },
    ],
  },
  {
    id: 'reef', name: 'Reef & Tide Pool', icon: '🪸', color: '#f4845f',
    entries: [
      { k: 'jellyfish', n: 'Jellyfish', s: 'Subphylum Medusozoa', e: '🪼', r: 2, c: [107], h: 'Oceans worldwide', d: 'Plankton', z: '1 mm – 2 m bell',
        t: 'A drifting bell with no brain, heart or bones — it\'s about 95% water.',
        f: 'Turritopsis dohrnii can revert to its youthful stage, earning it the name "immortal jellyfish".' },
      { k: 'anemone', n: 'Sea Anemone', s: 'Order Actiniaria', e: '🌺', r: 2, c: [108], h: 'Rocky shores and reefs', d: 'Carnivore', z: '1 cm – 1.5 m',
        t: 'A flower-like animal that waves stinging tentacles to catch passing prey, then pulls it into its central mouth.',
        f: 'Clownfish shelter among its tentacles, protected by a special mucus coat.' },
      { k: 'brain-coral', n: 'Brain Coral', s: 'Family Mussidae & kin', e: '🪸', r: 3, c: [109], h: 'Tropical reefs', d: 'Plankton & algae partners', z: 'Up to 1.8 m wide',
        t: 'A reef-builder whose grooved dome looks just like a human brain. It is made of thousands of tiny animals called polyps.',
        f: 'Some brain corals live for hundreds of years.' },
      { k: 'flatworm', n: 'Flatworm', s: 'Phylum Platyhelminthes', e: '🪱', r: 3, c: [110], h: 'Reefs, ponds and damp soil', d: 'Carnivore', z: 'Mostly 1–5 cm',
        t: 'A ribbon-thin worm that glides on a carpet of tiny hairs. Marine species ripple in dazzling warning colours.',
        f: 'Cut a planarian flatworm into pieces and each piece can regrow into a whole worm.' },
      { k: 'conch', n: 'Conch', s: 'Family Strombidae', e: '🐚', r: 2, c: [112], h: 'Warm shallow seas', d: 'Algae', z: '15–31 cm',
        t: 'A sea snail with a flaring, pink-lipped shell. Hold one to your ear, and people say you hear the ocean.',
        f: 'Queen conchs can make natural pearls, which are pink and very rare.' },
      { k: 'sea-slug', n: 'Sea Slug', s: 'Order Nudibranchia', e: '🐌', r: 3, c: [115], h: 'Reefs and rocky shores', d: 'Carnivore', z: '4 mm – 60 cm',
        t: 'A shell-less snail painted in neon colours. Some steal stinging cells from their prey to use as their own defence.',
        f: '"Nudibranch" means "naked gills" — the feathery tufts on its back.' },
      { k: 'chiton', n: 'Chiton', s: 'Class Polyplacophora', e: '🐚', r: 2, c: [116], h: 'Rocky intertidal shores', d: 'Algae', z: '1–33 cm',
        t: 'An oval mollusc armoured with eight overlapping plates. Pried off a rock, it curls up like a pill bug.',
        f: 'Some chitons have hundreds of tiny eyes with mineral lenses built into their shell plates.' },
      { k: 'nautilus', n: 'Nautilus', s: 'Family Nautilidae', e: '🐚', r: 3, c: [117], h: 'Deep Indo-Pacific reefs', d: 'Scavenger', z: 'Shell ~20 cm',
        t: 'A "living fossil" in a striped spiral shell that adjusts the gas in its chambers to rise and sink like a submarine.',
        f: 'A nautilus has up to 90 tentacles but no suckers.' },
      { k: 'crab', n: 'Crab', s: 'Infraorder Brachyura & king crabs', e: '🦀', r: 1, c: [118, 119, 121], h: 'Coasts and sea floors', d: 'Omnivore', z: 'Leg span up to 1.8 m',
        t: 'A sideways-scuttling crustacean in a hard shell, with claws for cracking, digging and fighting.',
        f: 'Crabs must moult their whole shell to grow, hiding while the new one hardens.' },
      { k: 'fiddler-crab', n: 'Fiddler Crab', s: 'Family Ocypodidae', e: '🦀', r: 2, c: [120], h: 'Mudflats and mangroves', d: 'Detritivore', z: 'Shell 1–5 cm',
        t: 'The male waves one enormous claw like a fiddler\'s bow to attract mates and warn rivals.',
        f: 'In some species, if a male loses his big claw, the small one grows huge instead.' },
      { k: 'hermit-crab', n: 'Hermit Crab', s: 'Superfamily Paguroidea', e: '🦀', r: 1, c: [125], h: 'Beaches and shallow seas', d: 'Scavenger', z: '1–15 cm',
        t: 'A soft-bodied crab that moves into empty snail shells, trading up for bigger homes as it grows.',
        f: 'Hermit crabs sometimes line up by size to swap shells in a "vacancy chain".' },
      { k: 'lobster', n: 'Lobster', s: 'Families Nephropidae & Palinuridae', e: '🦞', r: 2, c: [122, 123], h: 'Rocky sea floors', d: 'Omnivore', z: '25–60 cm',
        t: 'Clawed lobsters carry a crusher claw and a cutter claw; spiny lobsters defend themselves with long, spiky antennae.',
        f: 'Lobsters taste with their legs and have blue blood.' },
      { k: 'starfish', n: 'Starfish', s: 'Class Asteroidea', e: '⭐', r: 2, c: [327], h: 'Sea floors and tide pools', d: 'Carnivore', z: '1 cm – 1 m',
        t: 'A five-armed hunter that pries open clams and pushes its stomach out of its mouth to digest them.',
        f: 'Starfish have a simple eye at the tip of each arm.' },
      { k: 'sea-urchin', n: 'Sea Urchin', s: 'Class Echinoidea', e: '🌰', r: 2, c: [328], h: 'Rocky reefs and kelp forests', d: 'Algae', z: '3–30 cm',
        t: 'A living pincushion that walks on hundreds of tube feet and chews algae with a five-toothed jaw called "Aristotle\'s lantern".',
        f: 'Some sea urchins live for more than 100 years.' },
      { k: 'sea-cucumber', n: 'Sea Cucumber', s: 'Class Holothuroidea', e: '🥒', r: 3, c: [329], h: 'Sea floors worldwide', d: 'Detritivore', z: '1 cm – 3 m',
        t: 'A squishy vacuum cleaner of the sea floor. When threatened, some shoot out sticky threads — or even their own guts.',
        f: 'Pearlfish sometimes live inside sea cucumbers — entering through their bottoms.' },
      { k: 'clownfish', n: 'Clownfish', s: 'Subfamily Amphiprioninae', e: '🐠', r: 2, c: [393], h: 'Warm reefs of the Indo-Pacific', d: 'Omnivore', z: '7–17 cm',
        t: 'A bright orange fish that lives safely among the stinging tentacles of sea anemones.',
        f: 'Clownfish are born male; the dominant fish in a group can become female.' },
      { k: 'lionfish', n: 'Lionfish', s: 'Genus Pterois', e: '🐟', r: 3, c: [396], h: 'Indo-Pacific reefs; invasive in the Atlantic', d: 'Carnivore', z: '30–38 cm',
        t: 'A striped fish fanning out venomous spines like a lion\'s mane. It corners prey with its wide fins.',
        f: 'Released aquarium lionfish have invaded the Caribbean, where divers hunt them to protect reefs.' },
      { k: 'pufferfish', n: 'Pufferfish', s: 'Family Tetraodontidae', e: '🐡', r: 2, c: [397], h: 'Tropical seas', d: 'Omnivore', z: '2.5–60 cm',
        t: 'A slow swimmer that gulps water to balloon into a spiky ball too big to swallow.',
        f: 'Many puffers contain a toxin far deadlier than cyanide — yet specially licensed chefs in Japan serve it as "fugu".' },
      { k: 'rock-beauty', n: 'Rock Beauty', s: 'Holacanthus tricolor', e: '🐠', r: 3, c: [392], h: 'Caribbean reefs', d: 'Sponges', z: 'Up to 35 cm',
        t: 'A striking yellow-and-black angelfish of Caribbean reefs that feeds mainly on sponges.',
        f: 'Juveniles are yellow with a single black spot that grows into a large black patch.' },
    ],
  },
  {
    id: 'skies', name: 'Wild Skies', icon: '🦅', color: '#7d5a3c',
    entries: [
      { k: 'bald-eagle', n: 'Bald Eagle', s: 'Haliaeetus leucocephalus', e: '🦅', r: 3, c: [22], h: 'Lakes and coasts of North America', d: 'Fish', z: 'Wingspan 1.8–2.3 m',
        t: 'A mighty fish-snatching eagle and the national bird of the USA, recovered from near extinction.',
        f: 'Bald eagles build the largest nests of any North American bird — one weighed about 2 tonnes.' },
      { k: 'kite', n: 'Black Kite', s: 'Milvus migrans', e: '🦅', r: 1, c: [21], h: 'Towns, rivers and fields of the Old World', d: 'Carnivore & scavenger', z: 'Wingspan 1.3–1.55 m',
        t: 'A fork-tailed raptor that soars over cities and markets, snatching scraps with remarkable agility.',
        f: 'In Australia, "firehawk" kites have been seen spreading bushfires by carrying burning sticks.' },
      { k: 'vulture', n: 'Vulture', s: 'Families Accipitridae & Cathartidae', e: '🦅', r: 2, c: [23], h: 'Open country and mountains', d: 'Scavenger', z: 'Wingspan 1.7–3 m',
        t: 'Nature\'s clean-up crew. Powerful stomach acid lets it safely eat carcasses that would sicken other animals.',
        f: 'A Rüppell\'s vulture holds the record for the highest-flying bird, at about 11,300 m.' },
      { k: 'great-grey-owl', n: 'Great Grey Owl', s: 'Strix nebulosa', e: '🦉', r: 3, c: [24], h: 'Northern conifer forests', d: 'Voles', z: '61–84 cm',
        t: 'A huge, ghostly owl with a dish-shaped face that funnels sound, letting it hear voles tunnelling beneath deep snow.',
        f: 'It is one of the tallest owls, but much of its bulk is fluffy feathers.' },
      { k: 'peacock', n: 'Peacock', s: 'Pavo cristatus', e: '🦚', r: 2, c: [84], h: 'Forests and farmland of South Asia; parks', d: 'Omnivore', z: '1–2.25 m with train',
        t: 'The male fans a shimmering train of around 200 eye-spotted feathers to dazzle females.',
        f: 'The Indian peafowl is the national bird of India.' },
      { k: 'grouse', n: 'Grouse', s: 'Subfamily Tetraoninae', e: '🐦', r: 2, c: [80, 82, 83], h: 'Moors, forests and prairies', d: 'Herbivore', z: '30–60 cm',
        t: 'A plump ground bird whose males gather at dawn "leks" to strut, puff up and display for females.',
        f: 'The ruffed grouse drums its wings so fast it makes a low thump like a distant engine.' },
      { k: 'dipper', n: 'Dipper', s: 'Genus Cinclus', e: '🐦', r: 3, c: [20], h: 'Fast mountain streams', d: 'Aquatic insects', z: '17–20 cm',
        t: 'The only songbird that swims — it walks underwater along stream beds, gripping stones to hunt insect larvae.',
        f: 'A see-through third eyelid lets it see clearly underwater.' },
      { k: 'bee-eater', n: 'Bee-eater', s: 'Family Meropidae', e: '🐦', r: 2, c: [92], h: 'Open country of Africa, Asia & Europe', d: 'Bees and wasps', z: '17–35 cm',
        t: 'A rainbow-feathered aerial hunter that catches bees mid-flight, then whacks them on a branch to remove the sting.',
        f: 'Bee-eaters nest in tunnels they dig into sandy riverbanks.' },
      { k: 'coucal', n: 'Coucal', s: 'Genus Centropus', e: '🐦', r: 2, c: [91], h: 'Scrub of Africa, Asia & Australia', d: 'Carnivore', z: '30–60 cm',
        t: 'A large, skulking cuckoo with chestnut wings and a deep, booming "hoop-hoop" call.',
        f: 'Unlike many cuckoos, coucals raise their own chicks — in some species the male does most of the work.' },
    ],
  },
  {
    id: 'savanna', name: 'African Savanna', icon: '🦁', color: '#e09f3e',
    entries: [
      { k: 'lion', n: 'Lion', s: 'Panthera leo', e: '🦁', r: 3, c: [291], h: 'Savannas of Africa; Gir Forest, India', d: 'Carnivore', z: '1.2 m at shoulder',
        t: 'The only truly social big cat, living in family groups called prides. Its roar carries up to 8 km.',
        f: 'Lionesses do most of the hunting, often working as a team.' },
      { k: 'cheetah', n: 'Cheetah', s: 'Acinonyx jubatus', e: '🐆', r: 3, c: [293], h: 'Open grasslands of Africa', d: 'Carnivore', z: '70–90 cm at shoulder',
        t: 'The fastest land animal, reaching about 100 km/h in a few seconds. Black "tear lines" help cut the sun\'s glare.',
        f: 'Cheetahs can\'t roar — instead they chirp, purr and yelp.' },
      { k: 'leopard', n: 'Leopard', s: 'Panthera pardus', e: '🐆', r: 3, c: [288], h: 'Africa & Asia, forests to deserts', d: 'Carnivore', z: '45–80 cm at shoulder',
        t: 'A secretive, rosetted cat strong enough to haul prey heavier than itself up into a tree.',
        f: 'Most "black panthers" are leopards with dark fur — the spots are still there.' },
      { k: 'zebra', n: 'Zebra', s: 'Genus Equus', e: '🦓', r: 2, c: [340], h: 'Grasslands of Africa', d: 'Herbivore', z: '1.2–1.5 m at shoulder',
        t: 'A striped wild horse. No two zebras share the same stripe pattern.',
        f: 'Studies suggest the stripes help deter biting flies.' },
      { k: 'african-elephant', n: 'African Elephant', s: 'Genus Loxodonta', e: '🐘', r: 3, c: [386, 101], h: 'Savannas and forests of Africa', d: 'Herbivore', z: '3–4 m at shoulder',
        t: 'The largest land animal. Its trunk has tens of thousands of muscles and can lift logs or pluck a single blade of grass.',
        f: 'Elephants flap their huge ears to cool their blood.' },
      { k: 'hippo', n: 'Hippopotamus', s: 'Hippopotamus amphibius', e: '🦛', r: 3, c: [344], h: 'Rivers and lakes of Africa', d: 'Herbivore', z: 'Up to 1.6 m at shoulder',
        t: 'A massive river-dweller that spends the day submerged and comes ashore to graze at night.',
        f: 'Hippos ooze a reddish "blood sweat" that acts as a natural sunscreen.' },
      { k: 'hyena', n: 'Hyena', s: 'Family Hyaenidae', e: '🐕', r: 3, c: [276], h: 'Savannas of Africa & Asia', d: 'Carnivore', z: '70–90 cm at shoulder',
        t: 'A bone-crushing hunter with one of the strongest bites of any mammal. Spotted hyenas "giggle" when stressed.',
        f: 'Spotted hyenas live in female-led clans, and the females are larger than the males.' },
      { k: 'wild-dog', n: 'African Wild Dog', s: 'Lycaon pictus', e: '🐕', r: 3, c: [275], h: 'Savannas of Africa', d: 'Carnivore', z: '60–75 cm at shoulder',
        t: 'A "painted wolf" with a unique patchwork coat. Packs hunt with one of the highest success rates of any predator.',
        f: 'Pack members "vote" on when to set off hunting — by sneezing.' },
      { k: 'warthog', n: 'Warthog', s: 'Phacochoerus africanus', e: '🐗', r: 2, c: [343], h: 'Savannas of Africa', d: 'Omnivore', z: '65–85 cm at shoulder',
        t: 'A tusked wild pig that kneels on padded knees to graze and reverses into burrows so its tusks face out.',
        f: 'The "warts" are thick pads of skin that protect its face during fights.' },
      { k: 'gazelle', n: 'Gazelle', s: 'Genus Gazella & kin', e: '🦌', r: 2, c: [353], h: 'Grasslands and deserts', d: 'Herbivore', z: '55–95 cm at shoulder',
        t: 'A graceful antelope that "pronks" — springing high on stiff legs — to show predators it\'s too fit to chase.',
        f: 'Some gazelles can go their whole lives without drinking, getting water from plants.' },
      { k: 'impala', n: 'Impala', s: 'Aepyceros melampus', e: '🦌', r: 2, c: [352], h: 'Woodland savannas of Africa', d: 'Herbivore', z: '75–92 cm at shoulder',
        t: 'An agile antelope that can leap 3 metres high and 10 metres long, scattering its herd to confuse predators.',
        f: 'Impalas groom each other in turns — you scratch mine, I\'ll scratch yours.' },
      { k: 'hartebeest', n: 'Hartebeest', s: 'Alcelaphus buselaphus', e: '🦌', r: 3, c: [351], h: 'Grasslands of Africa', d: 'Herbivore', z: '1.1–1.5 m at shoulder',
        t: 'A long-faced antelope with bracket-shaped horns and a high-shouldered, sloping back.',
        f: 'Hartebeest post sentries on termite mounds to watch for predators.' },
      { k: 'meerkat', n: 'Meerkat', s: 'Suricata suricatta', e: '🦦', r: 3, c: [299], h: 'Kalahari Desert, southern Africa', d: 'Insects', z: '25–35 cm body',
        t: 'A tiny sentinel that stands tall on its hind legs to watch for eagles while its gang forages.',
        f: 'Meerkats have different alarm calls for threats from the air and from the ground.' },
      { k: 'mongoose', n: 'Mongoose', s: 'Family Herpestidae', e: '🦦', r: 2, c: [298], h: 'Africa & Asia, scrub to towns', d: 'Carnivore', z: '25–60 cm body',
        t: 'A quick, fearless hunter famous for facing down cobras with lightning dodges.',
        f: 'Special nerve receptors make mongooses partly resistant to snake venom.' },
      { k: 'ostrich', n: 'Ostrich', s: 'Struthio camelus', e: '🐦', r: 3, c: [9], h: 'Savannas and deserts of Africa', d: 'Omnivore', z: '2.1–2.8 m tall',
        t: 'The largest bird on Earth. It can\'t fly, but can sprint at about 70 km/h.',
        f: 'An ostrich\'s eye is bigger than its brain.' },
      { k: 'bustard', n: 'Bustard', s: 'Family Otididae', e: '🐦', r: 3, c: [138], h: 'Grasslands and dry plains', d: 'Omnivore', z: '40–150 cm',
        t: 'A stately ground bird of open plains. The great bustard is among the heaviest flying birds in the world.',
        f: 'Displaying male great bustards turn their feathers inside-out into a white "foam bath".' },
    ],
  },
  {
    id: 'forest', name: 'Forest & Mountain', icon: '🌲', color: '#386641',
    entries: [
      { k: 'brown-bear', n: 'Brown Bear', s: 'Ursus arctos', e: '🐻', r: 3, c: [294], h: 'Forests and mountains of the north', d: 'Omnivore', z: '1.5–2.8 m long',
        t: 'A humped powerhouse that fattens up on salmon and berries before sleeping through the winter.',
        f: 'The Kodiak bear, a brown bear subspecies, is one of the largest land carnivores.' },
      { k: 'black-bear', n: 'Black Bear', s: 'Ursus americanus', e: '🐻', r: 2, c: [295], h: 'Forests of North America', d: 'Omnivore', z: '1.2–2 m long',
        t: 'A skilled tree-climber that isn\'t always black — its coat can be brown, cinnamon or even creamy white.',
        f: 'The white "spirit bears" of Canada\'s rainforest are black bears with a rare gene.' },
      { k: 'grey-wolf', n: 'Grey Wolf', s: 'Canis lupus', e: '🐺', r: 3, c: [269], h: 'Forests, tundra and mountains', d: 'Carnivore', z: '0.6–0.9 m at shoulder',
        t: 'A cooperative hunter living in family packs. Howls help members find each other across great distances.',
        f: 'Every domestic dog descends from ancient wolves.' },
      { k: 'red-wolf', n: 'Red Wolf', s: 'Canis rufus', e: '🐺', r: 3, c: [271], h: 'SE United States (critically endangered)', d: 'Carnivore', z: '66–79 cm at shoulder',
        t: 'One of the world\'s most endangered canids, with only a few dozen roaming wild in North Carolina.',
        f: 'The look-alike maned wolf of South America is neither wolf nor fox, but a unique canid of its own.' },
      { k: 'coyote', n: 'Coyote', s: 'Canis latrans', e: '🐺', r: 2, c: [272], h: 'Deserts to cities of North America', d: 'Omnivore', z: '58–66 cm at shoulder',
        t: 'A clever, adaptable canid that has spread across North America and now lives in cities like Chicago and Los Angeles.',
        f: 'Coyotes sometimes team up with badgers to hunt ground squirrels.' },
      { k: 'red-fox', n: 'Red Fox', s: 'Vulpes vulpes', e: '🦊', r: 2, c: [277], h: 'Forests, farmland and cities', d: 'Omnivore', z: '45–90 cm body',
        t: 'A cunning hunter with a white-tipped tail. It pounces on mice hidden under snow by listening for them.',
        f: 'Foxes may use Earth\'s magnetic field to aim — their most successful pounces face north-east.' },
      { k: 'grey-fox', n: 'Grey Fox', s: 'Urocyon cinereoargenteus', e: '🦊', r: 2, c: [280], h: 'Woodland of the Americas', d: 'Omnivore', z: '50–70 cm body',
        t: 'A salt-and-pepper fox with curved claws that lets it climb trees like a cat.',
        f: 'It is one of the only canids able to climb trees.' },
      { k: 'lynx', n: 'Lynx', s: 'Genus Lynx', e: '🐈', r: 3, c: [287], h: 'Northern forests', d: 'Carnivore', z: '80–130 cm body',
        t: 'A tuft-eared forest cat with huge furry paws that work like snowshoes.',
        f: 'Canada lynx numbers rise and fall in a roughly 10-year cycle with snowshoe hares.' },
      { k: 'cougar', n: 'Cougar', s: 'Puma concolor', e: '🐆', r: 3, c: [286], h: 'Mountains and forests of the Americas', d: 'Carnivore', z: '60–90 cm at shoulder',
        t: 'A powerful, solitary cat that can leap about 5 metres straight up into a tree.',
        f: 'Puma, mountain lion, panther, catamount — it holds the record for the animal with the most names.' },
      { k: 'wild-boar', n: 'Wild Boar', s: 'Sus scrofa', e: '🐗', r: 2, c: [342], h: 'Forests of Europe, Asia & North Africa', d: 'Omnivore', z: '0.6–1.1 m at shoulder',
        t: 'The bristly wild ancestor of the farm pig. Its striped piglets blend into the forest floor.',
        f: 'Wild boar mothers raise their piglets together in groups called sounders.' },
      { k: 'badger', n: 'Badger', s: 'Genera Meles & Taxidea', e: '🦡', r: 2, c: [362], h: 'Woodland and grasslands', d: 'Omnivore', z: '60–90 cm',
        t: 'A stripe-faced digger that builds huge underground homes called setts, used by generation after generation.',
        f: 'Some badger setts are thought to be centuries old.' },
      { k: 'weasel', n: 'Weasel', s: 'Genus Mustela', e: '🦡', r: 2, c: [356], h: 'Fields, forests and hedgerows', d: 'Carnivore', z: '15–40 cm',
        t: 'A slim, fierce hunter small enough to chase mice down their own tunnels.',
        f: 'The least weasel is the smallest carnivore on Earth.' },
      { k: 'marmot', n: 'Marmot', s: 'Genus Marmota', e: '🐿️', r: 2, c: [336], h: 'Mountain meadows', d: 'Herbivore', z: '40–70 cm',
        t: 'A chunky ground squirrel of alpine meadows that whistles shrill alarms when eagles circle overhead.',
        f: 'Marmots can hibernate for up to eight months a year.' },
      { k: 'bighorn', n: 'Bighorn Sheep', s: 'Ovis canadensis', e: '🐏', r: 3, c: [349], h: 'Rocky Mountains', d: 'Herbivore', z: '0.8–1.1 m at shoulder',
        t: 'A mountain sheep whose rams clash curling horns at around 30 km/h in head-butting contests.',
        f: 'A ram\'s horns can weigh more than all the bones in its body.' },
      { k: 'ibex', n: 'Alpine Ibex', s: 'Capra ibex', e: '🐐', r: 3, c: [350], h: 'The Alps', d: 'Herbivore', z: '0.7–1 m at shoulder',
        t: 'A wild goat with enormous ridged horns that climbs near-vertical cliffs — even dam walls — to lick salt.',
        f: 'Once hunted down to about 100 animals, ibex now number in the tens of thousands.' },
      { k: 'bison', n: 'Bison', s: 'Genus Bison', e: '🦬', r: 3, c: [347], h: 'Prairies of North America; European forests', d: 'Herbivore', z: '1.5–2 m at shoulder',
        t: 'The heaviest land animal of North America, a shaggy giant that can still sprint at about 55 km/h.',
        f: 'Bison roll in dusty "wallows" to shed fur and fend off insects.' },
      { k: 'snow-leopard', n: 'Snow Leopard', s: 'Panthera uncia', e: '🐆', r: 3, c: [289], h: 'High mountains of Central Asia', d: 'Carnivore', z: '55–65 cm at shoulder',
        t: 'The "ghost of the mountains", a smoky-grey cat that wraps its thick tail around itself like a scarf.',
        f: 'Snow leopards can\'t roar; they greet each other with a puffing "chuff".' },
      { k: 'red-panda', n: 'Red Panda', s: 'Ailurus fulgens', e: '🦊', r: 3, c: [387], h: 'Himalayan bamboo forests', d: 'Herbivore (bamboo)', z: '50–64 cm body',
        t: 'A fiery-furred tree climber with a ringed tail. It was called "panda" before the giant panda was.',
        f: 'Like the giant panda, it has a "false thumb" — an extended wrist bone for gripping bamboo.' },
      { k: 'giant-panda', n: 'Giant Panda', s: 'Ailuropoda melanoleuca', e: '🐼', r: 3, c: [388], h: 'Mountain bamboo forests of China', d: 'Herbivore (bamboo)', z: '1.2–1.9 m long',
        t: 'A black-and-white bear that spends up to 14 hours a day munching bamboo.',
        f: 'A newborn panda is about 1/900th of its mother\'s weight — roughly the size of a stick of butter.' },
    ],
  },
  {
    id: 'primates', name: 'Primates', icon: '🐒', color: '#9c6644',
    entries: [
      { k: 'orangutan', n: 'Orangutan', s: 'Genus Pongo', e: '🦧', r: 3, c: [365], h: 'Rainforests of Borneo & Sumatra', d: 'Mostly fruit', z: '1.2–1.5 m tall',
        t: 'The largest tree-dwelling animal, a thoughtful red ape whose name means "person of the forest" in Malay.',
        f: 'Orangutans build a fresh leafy nest high in the trees to sleep in every night.' },
      { k: 'gorilla', n: 'Gorilla', s: 'Genus Gorilla', e: '🦍', r: 3, c: [366], h: 'Forests of Central Africa', d: 'Herbivore', z: '1.3–1.8 m standing',
        t: 'The largest primate. A silverback leads its family group and beats its chest to show strength.',
        f: 'Gorillas share about 98% of their DNA with humans.' },
      { k: 'chimpanzee', n: 'Chimpanzee', s: 'Pan troglodytes', e: '🐒', r: 3, c: [367], h: 'Forests of Africa', d: 'Omnivore', z: '1–1.7 m standing',
        t: 'A clever ape that makes tools — stripping twigs to fish termites from mounds and cracking nuts with stones.',
        f: 'Chimpanzees and bonobos are our closest living relatives.' },
      { k: 'gibbon', n: 'Gibbon', s: 'Family Hylobatidae', e: '🐒', r: 3, c: [368], h: 'Rainforests of SE Asia', d: 'Mostly fruit', z: '45–65 cm body',
        t: 'An acrobatic "lesser ape" that swings arm-over-arm through the canopy at up to 55 km/h.',
        f: 'Gibbon pairs sing loud duets each morning to defend their territory.' },
      { k: 'siamang', n: 'Siamang', s: 'Symphalangus syndactylus', e: '🐒', r: 3, c: [369], h: 'Rainforests of Sumatra & Malaysia', d: 'Herbivore', z: '75–90 cm body',
        t: 'The largest gibbon, with an inflatable throat sac that booms its song across the forest.',
        f: 'Siamang songs can be heard 2–3 km away.' },
      { k: 'macaque', n: 'Macaque', s: 'Genus Macaca', e: '🐒', r: 1, c: [373], h: 'Asia & North Africa, forests to cities', d: 'Omnivore', z: '40–70 cm body',
        t: 'A bold, adaptable monkey that thrives everywhere from snowy mountains to busy temples.',
        f: 'Japanese macaques warm up in hot springs during snowy winters.' },
      { k: 'langur', n: 'Langur', s: 'Genera Semnopithecus & Trachypithecus', e: '🐒', r: 1, c: [374], h: 'Forests and towns of South & SE Asia', d: 'Leaves', z: '50–80 cm body',
        t: 'A long-tailed, leaf-eating monkey with a black face, often seen lounging around temples.',
        f: 'Langurs have multi-chambered stomachs, a bit like cows, to digest tough leaves.' },
      { k: 'colobus', n: 'Colobus', s: 'Genus Colobus', e: '🐒', r: 3, c: [375], h: 'Forests of Africa', d: 'Leaves', z: '45–70 cm body',
        t: 'A black-and-white monkey with a flowing white cape that streams behind it as it leaps between trees.',
        f: '"Colobus" means "mutilated" in Greek, because it has only a stub for a thumb.' },
      { k: 'proboscis-monkey', n: 'Proboscis Monkey', s: 'Nasalis larvatus', e: '🐒', r: 3, c: [376], h: 'Mangrove forests of Borneo', d: 'Herbivore', z: '55–75 cm body',
        t: 'A pot-bellied monkey whose males sport an enormous drooping nose to amplify their calls.',
        f: 'It is an excellent swimmer, with partly webbed feet.' },
      { k: 'marmoset', n: 'Marmoset', s: 'Family Callitrichidae', e: '🐒', r: 3, c: [377], h: 'Forests of South America', d: 'Tree gum and insects', z: '12–20 cm body',
        t: 'A squirrel-sized monkey with ear tufts that gnaws holes in trees to feed on sap and gum.',
        f: 'Marmosets usually have twins, and the fathers help carry them.' },
      { k: 'capuchin', n: 'Capuchin', s: 'Genera Cebus & Sapajus', e: '🐒', r: 3, c: [378], h: 'Forests of Central & South America', d: 'Omnivore', z: '30–56 cm body',
        t: 'A clever monkey that uses stones as hammers and anvils to crack open nuts.',
        f: 'It is named after Capuchin friars, whose hooded robes resembled its cap of fur.' },
      { k: 'howler-monkey', n: 'Howler Monkey', s: 'Genus Alouatta', e: '🐒', r: 3, c: [379], h: 'Forests of Central & South America', d: 'Herbivore', z: '55–90 cm body',
        t: 'One of the loudest land animals — its roars can carry up to 5 km through the rainforest.',
        f: 'Howlers use their tails as a fifth hand to grip branches.' },
      { k: 'titi-monkey', n: 'Titi Monkey', s: 'Subfamily Callicebinae', e: '🐒', r: 3, c: [380], h: 'Amazon rainforest', d: 'Omnivore', z: '25–45 cm body',
        t: 'A fluffy, soft-voiced monkey whose bonded pairs sit side by side with their tails entwined.',
        f: 'Titi partners become stressed when separated from each other.' },
      { k: 'spider-monkey', n: 'Spider Monkey', s: 'Genus Ateles', e: '🐒', r: 3, c: [381], h: 'Rainforests of Central & South America', d: 'Mostly fruit', z: '40–60 cm body',
        t: 'A lanky acrobat with a gripping tail so strong it can hang by it alone.',
        f: 'The underside of its tail has a hairless, fingerprint-like pad for better grip.' },
      { k: 'squirrel-monkey', n: 'Squirrel Monkey', s: 'Genus Saimiri', e: '🐒', r: 3, c: [382], h: 'Rainforests of Central & South America', d: 'Omnivore', z: '25–35 cm body',
        t: 'A small, bright-eyed monkey that travels in noisy troops that can number in the hundreds.',
        f: 'For its body size, it has one of the largest brains of any primate.' },
      { k: 'baboon', n: 'Baboon', s: 'Genus Papio', e: '🐒', r: 3, c: [372], h: 'Savannas and hills of Africa & Arabia', d: 'Omnivore', z: '50–115 cm body',
        t: 'A dog-faced monkey living in large troops full of complex friendships and rivalries.',
        f: 'Baboons have learned to tell real English words from made-up ones.' },
      { k: 'patas-monkey', n: 'Patas Monkey', s: 'Erythrocebus patas', e: '🐒', r: 3, c: [371], h: 'Savannas of Africa', d: 'Omnivore', z: '50–85 cm body',
        t: 'The fastest primate, a long-legged monkey that can dash across grassland at about 55 km/h.',
        f: 'Patas monkeys spend most of their time on the ground rather than in trees.' },
      { k: 'guenon', n: 'Guenon', s: 'Genus Cercopithecus', e: '🐒', r: 3, c: [370], h: 'Forests of Africa', d: 'Omnivore', z: '30–70 cm body',
        t: 'A colourful, long-tailed monkey whose bold face markings may help each species recognise its own kind.',
        f: 'Some monkeys in this family have different alarm calls for leopards, eagles and snakes.' },
      { k: 'ring-tailed-lemur', n: 'Ring-tailed Lemur', s: 'Lemur catta', e: '🐒', r: 3, c: [383], h: 'Madagascar', d: 'Omnivore', z: '39–46 cm body',
        t: 'A sunbathing primate that raises its black-and-white striped tail like a flag to keep its troop together.',
        f: 'Males have "stink fights", wafting scented tails at each other.' },
      { k: 'indri', n: 'Indri', s: 'Indri indri', e: '🐒', r: 4, c: [384], h: 'Rainforests of eastern Madagascar', d: 'Herbivore', z: '64–72 cm body',
        t: 'The largest living lemur, whose eerie, whale-like song echoes across Madagascar\'s forests.',
        f: 'Indris don\'t survive in captivity — the only way to see one is in the wild.' },
    ],
  },
  {
    id: 'rainforest', name: 'Rainforest', icon: '🌴', color: '#0f7b5f',
    entries: [
      { k: 'tiger', n: 'Tiger', s: 'Panthera tigris', e: '🐅', r: 3, c: [292], h: 'Forests of Asia', d: 'Carnivore', z: '0.8–1.1 m at shoulder',
        t: 'The largest cat on Earth. Each tiger\'s stripes are unique — and even its skin is striped.',
        f: 'Unlike most cats, tigers love water and are strong swimmers.' },
      { k: 'jaguar', n: 'Jaguar', s: 'Panthera onca', e: '🐆', r: 3, c: [290], h: 'Rainforests of Central & South America', d: 'Carnivore', z: '63–76 cm at shoulder',
        t: 'The Americas\' biggest cat, with a bite strong enough to pierce turtle shells.',
        f: 'Jaguar rosettes often have small spots inside them — a leopard\'s usually don\'t.' },
      { k: 'sloth', n: 'Three-toed Sloth', s: 'Genus Bradypus', e: '🦥', r: 3, c: [364], h: 'Rainforests of Central & South America', d: 'Leaves', z: '45–60 cm',
        t: 'The slowest mammal, hanging upside down so still that algae grows in its fur and tints it green.',
        f: 'Sloths climb down only about once a week — to go to the toilet.' },
      { k: 'asian-elephant', n: 'Asian Elephant', s: 'Elephas maximus', e: '🐘', r: 2, c: [385], h: 'Forests and grasslands of South & SE Asia', d: 'Herbivore', z: '2.5–3 m at shoulder',
        t: 'A small-eared elephant revered across Asia, with a single "finger" at the tip of its trunk.',
        f: 'Only some male Asian elephants grow tusks.' },
      { k: 'sloth-bear', n: 'Sloth Bear', s: 'Melursus ursinus', e: '🐻', r: 3, c: [297], h: 'Forests of India & Sri Lanka', d: 'Termites and fruit', z: '1.4–1.9 m long',
        t: 'A shaggy bear that vacuums termites out of their mounds through a gap in its front teeth.',
        f: 'Mothers carry their cubs on their backs for months.' },
      { k: 'dhole', n: 'Dhole', s: 'Cuon alpinus', e: '🐕', r: 3, c: [274], h: 'Forests of South & SE Asia', d: 'Carnivore', z: '42–55 cm at shoulder',
        t: 'A rust-red "whistling dog" that hunts in packs and calls to its clan with bird-like whistles.',
        f: 'Dholes are endangered, with only a few thousand left in the wild.' },
      { k: 'armadillo', n: 'Armadillo', s: 'Order Cingulata', e: '🦔', r: 2, c: [363], h: 'The Americas, grassland to rainforest', d: 'Insects', z: '13–150 cm',
        t: 'An armoured digger. The three-banded armadillo can roll itself into a near-perfect ball.',
        f: 'Nine-banded armadillos almost always give birth to identical quadruplets.' },
      { k: 'toucan', n: 'Toucan', s: 'Family Ramphastidae', e: '🐦', r: 3, c: [96], h: 'Rainforests of Central & South America', d: 'Mostly fruit', z: '30–65 cm',
        t: 'A rainforest bird with a gigantic, colourful bill that is surprisingly light — mostly hollow.',
        f: 'Toucans use their big bills like radiators to shed body heat.' },
      { k: 'macaw', n: 'Macaw', s: 'Tribe Arini', e: '🦜', r: 3, c: [88], h: 'Rainforests of Central & South America', d: 'Seeds and nuts', z: '30–100 cm',
        t: 'A dazzling, long-tailed parrot that cracks hard nuts with its powerful beak and flies in noisy pairs.',
        f: 'Macaws eat clay from riverbanks, possibly for sodium or to neutralise toxins.' },
      { k: 'hornbill', n: 'Hornbill', s: 'Family Bucerotidae', e: '🐦', r: 3, c: [93], h: 'Tropical forests of Africa & Asia', d: 'Omnivore', z: '30–130 cm',
        t: 'A big-billed bird topped with a helmet-like casque. The female seals herself inside a tree hole to nest.',
        f: 'The great hornbill is the state bird of Kerala, India.' },
      { k: 'jacamar', n: 'Jacamar', s: 'Family Galbulidae', e: '🐦', r: 3, c: [95], h: 'Tropical forests of Central & South America', d: 'Butterflies and insects', z: '14–34 cm',
        t: 'A glittering, long-billed bird that snaps butterflies and dragonflies right out of the air.',
        f: 'Jacamars beat captured butterflies against a branch to knock off the wings.' },
    ],
  },
  {
    id: 'aussie', name: 'Down Under', icon: '🦘', color: '#bc4b31',
    entries: [
      { k: 'koala', n: 'Koala', s: 'Phascolarctos cinereus', e: '🐨', r: 3, c: [105], h: 'Eucalyptus forests of Australia', d: 'Eucalyptus leaves', z: '60–85 cm',
        t: 'A sleepy marsupial that dozes up to 20 hours a day to save energy from its low-nutrient diet.',
        f: 'Koala fingerprints are almost identical to human ones.' },
      { k: 'wallaby', n: 'Wallaby', s: 'Family Macropodidae', e: '🦘', r: 3, c: [104], h: 'Australia & New Guinea', d: 'Herbivore', z: '45–105 cm body',
        t: 'A smaller cousin of the kangaroo that bounds on powerful hind legs and balances with its thick tail.',
        f: 'Joeys are born about the size of a jellybean and crawl into their mother\'s pouch.' },
      { k: 'wombat', n: 'Wombat', s: 'Family Vombatidae', e: '🐻', r: 3, c: [106], h: 'Forests and grasslands of Australia', d: 'Herbivore', z: '70–120 cm',
        t: 'A stocky burrowing marsupial whose backwards-facing pouch keeps dirt out while it digs.',
        f: 'Wombats produce cube-shaped poop.' },
      { k: 'platypus', n: 'Platypus', s: 'Ornithorhynchus anatinus', e: '🦆', r: 3, c: [103], h: 'Streams of eastern Australia', d: 'Carnivore', z: '40–60 cm',
        t: 'An egg-laying mammal with a duck bill, beaver tail and otter feet. It hunts with eyes closed, sensing the electric signals of prey.',
        f: 'Males have venomous spurs, and platypus fur glows under UV light.' },
      { k: 'echidna', n: 'Echidna', s: 'Family Tachyglossidae', e: '🦔', r: 3, c: [102], h: 'Australia & New Guinea', d: 'Ants and termites', z: '30–45 cm',
        t: 'A spiny, egg-laying mammal that slurps ants with a long, sticky tongue.',
        f: 'A baby echidna is called a "puggle".' },
      { k: 'dingo', n: 'Dingo', s: 'Canis dingo', e: '🐕', r: 3, c: [273], h: 'Outback Australia', d: 'Carnivore', z: '50–60 cm at shoulder',
        t: 'Australia\'s wild dog, which rarely barks but howls — and can rotate its wrists to climb.',
        f: 'Australia\'s Dingo Fence stretches over 5,000 km, one of the longest structures on Earth.' },
      { k: 'black-swan', n: 'Black Swan', s: 'Cygnus atratus', e: '🦢', r: 2, c: [100], h: 'Wetlands of Australia', d: 'Herbivore', z: '1.1–1.4 m',
        t: 'A jet-black swan with a red bill and white wing tips, the emblem of Western Australia.',
        f: 'Europeans long believed all swans were white, so "black swan" came to mean the impossible.' },
      { k: 'cockatoo', n: 'Cockatoo', s: 'Family Cacatuidae', e: '🦜', r: 2, c: [89], h: 'Woodland of Australia', d: 'Seeds', z: '30–60 cm',
        t: 'A crested parrot that raises its yellow crest when excited. Wild flocks are famously loud and mischievous.',
        f: 'Sydney\'s cockatoos learned to open wheelie bins, and the trick spread between neighbourhoods.' },
      { k: 'lorikeet', n: 'Lorikeet', s: 'Genus Trichoglossus', e: '🦜', r: 2, c: [90], h: 'Forests and gardens of Australia & the Pacific', d: 'Nectar and pollen', z: '25–30 cm',
        t: 'A rainbow-coloured parrot with a brush-tipped tongue for lapping up nectar and pollen.',
        f: 'Lorikeets help pollinate eucalyptus trees as they feed.' },
      { k: 'frilled-lizard', n: 'Frilled Lizard', s: 'Chlamydosaurus kingii', e: '🦎', r: 3, c: [43], h: 'Woodland of northern Australia & New Guinea', d: 'Carnivore', z: '70–90 cm',
        t: 'When threatened, it flares a huge frill around its neck, gapes its mouth — then sprints off on its hind legs.',
        f: 'The frill is a flap of skin held up by long spines of cartilage.' },
    ],
  },
  {
    id: 'polar', name: 'Frozen Poles', icon: '❄️', color: '#5fa8d3',
    entries: [
      { k: 'polar-bear', n: 'Polar Bear', s: 'Ursus maritimus', e: '🐻‍❄️', r: 3, c: [296], h: 'Arctic sea ice', d: 'Seals', z: '2–3 m long',
        t: 'The largest land carnivore, hunting seals from the sea ice. Its fur looks white, but its skin is black.',
        f: 'Polar bear hairs are actually hollow and transparent, not white.' },
      { k: 'arctic-fox', n: 'Arctic Fox', s: 'Vulpes lagopus', e: '🦊', r: 3, c: [279], h: 'Arctic tundra', d: 'Omnivore', z: '46–68 cm body',
        t: 'A fluffy fox whose coat turns snow-white in winter and brown-grey in summer.',
        f: 'Its fur is so warm it doesn\'t start shivering until about −70 °C.' },
      { k: 'arctic-wolf', n: 'Arctic Wolf', s: 'Canis lupus arctos', e: '🐺', r: 3, c: [270], h: 'High Arctic of Canada & Greenland', d: 'Carnivore', z: '65–80 cm at shoulder',
        t: 'A snow-white wolf of the far north that survives months of darkness and bitter cold.',
        f: 'Having met so few humans, Arctic wolves are often unafraid of people.' },
      { k: 'king-penguin', n: 'King Penguin', s: 'Aptenodytes patagonicus', e: '🐧', r: 3, c: [145], h: 'Sub-Antarctic islands', d: 'Fish and squid', z: '70–100 cm tall',
        t: 'The second-largest penguin, with a golden neck patch. It balances its egg on its feet under a warm belly fold.',
        f: 'King penguins can dive deeper than 300 metres.' },
      { k: 'ptarmigan', n: 'Ptarmigan', s: 'Genus Lagopus', e: '🐦', r: 3, c: [81], h: 'Arctic tundra and high mountains', d: 'Herbivore', z: '31–40 cm',
        t: 'A grouse that turns white in winter and grows feathered "snowshoe" feet.',
        f: 'Ptarmigan burrow into snowdrifts to sleep, using the snow as insulation.' },
    ],
  },
  {
    id: 'desert', name: 'Deserts', icon: '🌵', color: '#d4a373',
    entries: [
      { k: 'camel', n: 'Dromedary Camel', s: 'Camelus dromedarius', e: '🐪', r: 2, c: [354], h: 'Deserts of Africa, Arabia & India', d: 'Herbivore', z: '1.8–2 m at shoulder',
        t: 'A one-humped "ship of the desert". Its hump stores fat, not water, as an energy reserve.',
        f: 'A thirsty camel can drink over 100 litres of water in about 10 minutes.' },
      { k: 'kit-fox', n: 'Kit Fox', s: 'Vulpes macrotis', e: '🦊', r: 3, c: [278], h: 'Deserts of SW North America', d: 'Omnivore', z: '45–54 cm body',
        t: 'A tiny desert fox with huge ears that shed heat and pinpoint prey in the dark.',
        f: 'It spends hot days underground in dens with several entrances.' },
      { k: 'gila-monster', n: 'Gila Monster', s: 'Heloderma suspectum', e: '🦎', r: 3, c: [45], h: 'Deserts of the SW USA & Mexico', d: 'Eggs and small animals', z: '35–56 cm',
        t: 'A bead-scaled, pink-and-black venomous lizard that can survive on just a few big meals a year.',
        f: 'A compound in its saliva inspired a medicine for type 2 diabetes.' },
      { k: 'sidewinder', n: 'Sidewinder', s: 'Crotalus cerastes', e: '🐍', r: 3, c: [68], h: 'Sandy deserts of the SW USA & Mexico', d: 'Carnivore', z: '45–80 cm',
        t: 'A small rattlesnake that throws its body sideways in S-shaped loops to glide across hot, loose sand.',
        f: 'It leaves J-shaped tracks and has horn-like scales over its eyes.' },
      { k: 'horned-viper', n: 'Horned Viper', s: 'Cerastes cerastes', e: '🐍', r: 3, c: [66], h: 'Sahara and Arabian deserts', d: 'Carnivore', z: '30–85 cm',
        t: 'A sand-coloured viper with spiky "horns" above its eyes that buries itself in sand to ambush prey.',
        f: 'It warns intruders by rubbing its rough scales together to make a rasping sound.' },
      { k: 'scorpion', n: 'Scorpion', s: 'Order Scorpiones', e: '🦂', r: 2, c: [71], h: 'Deserts and tropical forests', d: 'Carnivore', z: '1–23 cm',
        t: 'An eight-legged hunter armed with grasping pincers and a venomous stinger arched over its back.',
        f: 'Scorpions glow bright blue-green under ultraviolet light.' },
    ],
  },
  {
    id: 'relics', name: 'Ancient Relics', icon: '🦴', color: '#b08d57',
    entries: [
      { k: 'triceratops', n: 'Triceratops', s: 'Triceratops horridus', e: '🦕', r: 4, c: [51], h: 'Museums — extinct for 66 million years', d: 'Herbivore', z: '8–9 m long',
        t: 'A three-horned, frilled giant from the last days of the dinosaurs. Scan a museum skeleton or model to register it.',
        f: 'Its skull was among the largest of any land animal — up to about 2.5 m long.' },
      { k: 'trilobite', n: 'Trilobite', s: 'Class Trilobita', e: '🦴', r: 4, c: [69], h: 'Fossil beds — extinct for 252 million years', d: 'Varied', z: '1 mm – 70 cm',
        t: 'An armoured sea creature that thrived for nearly 300 million years. Scan a fossil to register it.',
        f: 'Trilobites had some of the earliest complex eyes, with lenses made of the mineral calcite.' },
    ],
  },
];

// Flat, numbered list (#001, #002 ...) in album order.
export const ENTRIES = [];
for (const set of SETS) {
  for (const e of set.entries) {
    e.no = ENTRIES.length + 1;
    e.set = set.id;
    ENTRIES.push(e);
  }
}
export const BY_KEY = Object.fromEntries(ENTRIES.map((e) => [e.k, e]));

// ImageNet classes 0-397 are animals (plus two fossils); 398+ are objects.
export const ANIMAL_CLASS_LIMIT = 398;
